## **import libraries & upload data**

In [2]:
import pandas as pd
import numpy as np

In [3]:
re=pd.read_csv('propertyfinder.csv')

C:\Users\dell\AppData\Local\Temp\ipykernel_18008\3337464109.py:1: DtypeWarning: Columns (0: completion_status) have mixed types. Specify dtype option on import or set low_memory=False.
  re=pd.read_csv('propertyfinder.csv')

## **adjust display options**

In [4]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.options.display.float_format = '{:,.2f}'.format

## **data understanding**

In [5]:
re.shape

(39713, 53)

In [6]:
re.info()

<class 'pandas.DataFrame'>
RangeIndex: 39713 entries, 0 to 39712
Data columns (total 53 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   listing_id           39712 non-null  str
 1   internal_id          39712 non-null  float64
 2   category             39713 non-null  str
 3   listing_type         39713 non-null  str
 4   detail_url           39712 non-null  str
 5   property_type        39712 non-null  str
 6   offering_type        39712 non-null  str
 7   completion_status    19763 non-null  str
 8   title                39712 non-null  str
 9   price_egp            39712 non-null  float64
 10  price_period         39712 non-null  str
 11  price_currency       39713 non-null  str
 12  location_full        39712 non-null  str
 13  city                 39712 non-null  str
 14  town                 39712 non-null  str
 15  district             39366 non-null  str
 16  subdistrict          32954 non-null  str
 17  lat                  39712 non-null  float64
 18  lon                  39712 non-null  float64
 19  bedrooms             39678 non-null  str
 20  bathrooms            39683 non-null  str
 21  area_value           39712 non-null  float64
 22  area_unit            39713 non-null  str
 23  furnished            31328 non-null  str
 24  listing_level        39712 non-null  str
 25  is_premium           39713 non-null  bool
 26  is_verified          39713 non-null  bool
 27  is_featured          39713 non-null  bool
 28  is_new_construction  39713 non-null  bool
 29  is_direct_from_dev   39713 non-null  bool
 30  is_exclusive         39713 non-null  bool
 31  listed_date          39712 non-null  str
 32  images_count         39713 non-null  int64
 33  has_view_360         39713 non-null  bool
 34  video_url            202 non-null    str
 35  reference            39712 non-null  str
 36  rera                 0 non-null      float64
 37  description          39712 non-null  str
 38  amenities            39680 non-null  str
 39  payment_method       19939 non-null  str
 40  agent_id             39712 non-null  float64
 41  agent_name           39705 non-null  str
 42  agent_email          39712 non-null  str
 43  agent_is_super       39713 non-null  bool
 44  agent_languages      9172 non-null   str
 45  broker_id            39712 non-null  float64
 46  broker_name          39712 non-null  str
 47  broker_email         39510 non-null  str
 48  broker_phone         39510 non-null  float64
 49  contact_phone        39712 non-null  float64
 50  contact_whatsapp     39712 non-null  float64
 51  contact_email        39712 non-null  str
 52  scraped_at           39713 non-null  str
dtypes: bool(8), float64(11), int64(1), str(33)
memory usage: 75.2 MB

In [7]:
re.head()

,listing_id,internal_id,category,listing_type,detail_url,property_type,offering_type,completion_status,title,price_egp,price_period,price_currency,location_full,city,town,district,subdistrict,lat,lon,bedrooms,bathrooms,area_value,area_unit,furnished,listing_level,is_premium,is_verified,is_featured,is_new_construction,is_direct_from_dev,is_exclusive,listed_date,images_count,has_view_360,video_url,reference,rera,description,amenities,payment_method,agent_id,agent_name,agent_email,agent_is_super,agent_languages,broker_id,broker_name,broker_email,broker_phone,contact_phone,contact_whatsapp,contact_email,scraped_at
0,F7QB31CGWE509V2W7DF2GARB2C,"56,009,081.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/duple...,Duplex,Residential for Sale,completed,Garden Villa - Lake View Boutique - Prime Loca...,"24,500,000.00",sell,EGP,"The Lakeview Boutique Villas, 5th Settlement C...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.04,31.53,3,6,445.00,sqm,NaN,premium,True,False,False,False,False,False,2026-03-03T19:15:06Z,6,False,NaN,F7QB31CGWE509V2W7DF2GARB2C,NaN,Garden Villa for Sale – Featured in Lake View ...,Balcony | Built in Wardrobes | Covered Parking...,cash,"58,866.00",pierre osama,pierre.Osama@spade-consultancy.com,False,NaN,"5,758.00",Spade consultancy,mohmedg.sedik@gmail.com,"1,001,436,511.00","201,201,801,443.00","20,221,257,340.00",pierre.Osama@spade-consultancy.com,2026-03-04T14:20:33.281007
1,K1JC3D6N57ED52N3VX1QQKHHXG,"56,247,925.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,off_plan,For Sale: Finished Apartment+ ACs in Village West,"5,145,000.00",sell,EGP,"Village West, Sheikh Zayed Compounds, Sheikh Z...",Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Village West,30.05,31.02,2,2,123.00,sqm,PARTLY,premium,True,False,False,False,False,False,2026-03-04T11:24:23Z,10,False,NaN,rb304,NaN,For Sale: Finished Apartment with ACs in Villa...,Balcony | Built in Wardrobes | Central A/C | C...,cash,"67,166.00",Rana Bahaa ElDeen,ranoushamer901@gmail.com,False,NaN,492.00,Abrag Real Estate,snawara71@gmail.com,"201,001,188,088.00","201,007,169,666.00","20,221,257,340.00",ranoushamer901@gmail.com,2026-03-04T14:20:33.281007
2,Q6GEB8T6PZTJGNNPWA5PX3JCWR,"56,253,883.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,UnderMarket Price for Apt. 250 RTM PrimeLocation,"10,800,000.00",sell,EGP,"Palm Hills New Cairo, 5th Settlement Compounds...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.01,31.58,4,4,250.00,sqm,NaN,premium,True,False,False,False,False,False,2026-03-04T14:03:51Z,13,False,NaN,250pncash,NaN,Palm Hills New Cairo Apartment BUA: 250sqm 4 B...,Balcony | Built in Wardrobes | Central A/C | C...,cash,"47,158.00",Ashraf Shaaban,ashrafsobhy99@hotmail.com,False,English | Arabic,"5,279.00",Premises,mahmouddessam@hotmail.com,"201,005,133,389.00","201,090,963,241.00","20,221,257,340.00",ashrafsobhy99@hotmail.com,2026-03-04T14:20:33.281007
3,PPH0852SAB266X6GSVATJP4F0M,"56,250,852.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,lowest price 2bds fullyfurnished @ lake view,"10,500,000.00",sell,EGP,"Lake View Residence, 5th Settlement Compounds,...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.03,31.54,2,2,136.00,sqm,YES,premium,True,False,False,False,False,False,2026-03-04T12:38:11Z,11,False,NaN,PPH0852SAB266X6GSVATJP4F0M,NaN,Lake View Residence 136 sqm Fully Finished Ren...,Balcony | Built in Wardrobes | Central A/C | C...,cash,"63,401.00",ebrahim hossam,ebrahim.hossam@spade-consultancy.com,False,NaN,"5,758.00",Spade consultancy,mohmedg.sedik@gmail.com,"1,001,436,511.00","201,070,115,211.00","20,221,257,340.00",ebrahim.hossam@spade-consultancy.com,2026-03-04T14:20:33.281007
4,QCSA4TNDEBBV7BNY8ANST3TB50,"55,995,764.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/villa...,Villa,Residential for Sale,completed,Exclusive Type M with Lowest Price RTM in PNC,"19,500,000.00",sell,EGP,"Palm Hills New Cairo, 5th Settlement Compounds...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.01,31.58,4,4,255.00,sqm,NaN,premium,True,False,False,False,False,False,2026-03-03T09:45:41Z,17,False,NaN,VillTyM,NaN,Palm Hills New Cairo Type M BUA: 255sqm LAND: ...,Balcony | Built in Wardrobes | Central A/C | C...,cash,"47,158.00",Ashraf Shaaban,ashrafsobhy99@hotmail.com,False,English | Arabic,"5,279.00",Premises,mahmouddessam@hotmail.com,"201,005,133,389.00","201,090,963,241.00","20,221,257,340.00",ashrafsobhy99@hotmail.com,2026-03-04T14:20:33.281007

In [8]:
re.isnull().sum().sort_values(ascending=False)

rera                   39713
video_url              39511
agent_languages        30541
completion_status      19950
payment_method         19774
furnished               8385
subdistrict             6759
district                 347
broker_email             203
broker_phone             203
bedrooms                  35
amenities                 33
bathrooms                 30
agent_name                 8
city                       1
detail_url                 1
location_full              1
listing_id                 1
property_type              1
offering_type              1
internal_id                1
contact_email              1
agent_email                1
broker_name                1
lat                        1
price_egp                  1
price_period               1
town                       1
lon                        1
title                      1
agent_id                   1
description                1
area_value                 1
reference                  1
listed_date                1
listing_level              1
contact_phone              1
contact_whatsapp           1
broker_id                  1
category                   0
listing_type               0
price_currency             0
has_view_360               0
is_featured                0
is_new_construction        0
area_unit                  0
is_direct_from_dev         0
is_exclusive               0
images_count               0
is_premium                 0
is_verified                0
agent_is_super             0
scraped_at                 0
dtype: int64

In [9]:
re.describe()

,internal_id,price_egp,lat,lon,area_value,images_count,rera,agent_id,broker_id,broker_phone,contact_phone,contact_whatsapp
count,"39,712.00","39,712.00","39,712.00","39,712.00","39,712.00","39,713.00",0.00,"39,712.00","39,712.00","39,510.00","39,712.00","39,712.00"
mean,"45,379,476.59","7,988,803.42",29.98,31.32,218.48,12.28,NaN,"53,288.36","4,144.89","151,703,584,082.74","303,189,659,577,194.75","63,187,517,500.30"
std,"18,804,978.55","24,492,789.87",0.60,0.86,781.82,4.82,NaN,"17,909.36","10,005.16","86,252,580,080.09","60,379,162,250,923,728.00","76,980,188,309.46"
min,"2,908,155.00","1,300.00",25.07,25.48,1.00,0.00,NaN,"5,500.00",55.00,"1,000,009,081.00","201,000,001,398.00","20,221,257,340.00"
25%,"52,454,285.00","65,000.00",30.00,31.02,130.00,10.00,NaN,"42,365.00","1,614.00","201,000,137,017.00","201,032,992,760.00","20,221,257,340.00"
50%,"54,760,999.50","600,000.00",30.03,31.50,175.00,11.00,NaN,"57,459.00","4,208.00","201,026,694,777.00","201,102,191,494.00","20,221,257,340.00"
75%,"55,758,653.75","9,113,125.00",30.06,31.55,245.00,14.00,NaN,"68,818.00","5,657.00","201,117,033,304.00","201,145,564,556.00","20,221,257,340.00"
max,"56,493,417.00","1,000,000,000.00",31.50,34.90,"96,600.00",30.00,NaN,"73,845.00","179,957.00","201,558,194,855.00","12,032,281,120,109,799,424.00","201,559,777,173.00"

In [10]:
re.describe(include='object')

C:\Users\dell\AppData\Local\Temp\ipykernel_18008\4220137062.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  re.describe(include='object')

,listing_id,category,listing_type,detail_url,property_type,offering_type,completion_status,title,price_period,price_currency,location_full,city,town,district,subdistrict,bedrooms,bathrooms,area_unit,furnished,listing_level,listed_date,video_url,reference,description,amenities,payment_method,agent_name,agent_email,agent_languages,broker_name,broker_email,contact_email,scraped_at
count,39712,39713,39713,39712,39712,39712,19763,39712,39712,39713,39712,39712,39712,39366,32954,39678,39683,39713,31328,39712,39712,202,39712,39712,39680,19939,39705,39712,9172,39712,39510,39712,39713
unique,39712,2,2,39712,19,2,4,32700,2,1,1959,12,67,519,1134,9,9,1,3,3,36255,154,39645,35312,17995,3,2659,2732,30,776,770,2732,4736
top,F7QB31CGWE509V2W7DF2GARB2C,rent,property,https://www.propertyfinder.eg/en/plp/buy/duple...,Apartment,Residential for Rent,completed,Hotel apartment for rent inAlRehab fully furni...,monthly,EGP,"Mivida, 5th Settlement Compounds, The 5th Sett...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,3,3,sqm,YES,standard,2026-02-09T11:27:08Z,https://www.youtube.com/watch?v=ouXREODabm0,7,We offer all real estate services in some of t...,Balcony | Built in Wardrobes | Central A/C | C...,cash,FORTUNE REALTY,fourtunerealityeg@gmail.com,English | Arabic,Egypt Best Properties,info@egyptbestproperties.com,fourtunerealityeg@gmail.com,2026-03-04T14:35:10.896367
freq,1,19910,39712,1,25211,19910,10135,215,19910,39713,2433,25865,19738,13082,11671,18189,14168,39713,12719,31249,13,7,5,67,1467,12806,576,576,6679,1490,1490,576,25

In [11]:
re[['internal_id', 'agent_id', 'broker_id',
    'broker_phone', 'contact_phone', 'contact_whatsapp']].nunique()

internal_id         39712
agent_id             2773
broker_id             776
broker_phone          769
contact_phone        2483
contact_whatsapp      422
dtype: int64

In [12]:
re['property_type'].unique()

<ArrowStringArray>
[         'Duplex',       'Apartment',           'Villa',               nan,
       'Penthouse',      'Twin House',       'Townhouse',          'Chalet',
          'iVilla', 'Hotel Apartment',  'Whole Building',      'Half Floor',
            'Land',  'Bulk Sale Unit',           'Cabin',            'Roof',
          'Palace',      'Full Floor',  'Bulk Rent Unit',        'Bungalow']
Length: 20, dtype: str

In [13]:
re['completion_status'].unique()

# completed:  (Resale)عقار مكتمل البناء ومباع عن طريق إعادة البيع

# off_plan:  (Resale) عقار قيد الإنشاء أو تحت التخطيط

# completed_primary:  (Primary)عقار مكتمل الجاهزية ومباع مباشرة من الشركة /المطور

# off_plan_primary: عقار تحت الإنشاء ومباع مباشرة من المطور مع خطط سداد.

<ArrowStringArray>
['completed', 'off_plan', nan, 'completed_primary', 'off_plan_primary']
Length: 5, dtype: str

### extreme values invastigation

In [14]:
sell = re[re['category'] == 'buy'].copy()
rent = re[re['category'] == 'rent'].copy()

In [15]:
sell.nsmallest(20, 'price_egp')[
    ['price_egp', 'property_type', 'area_value',
     'bedrooms', 'bathrooms', 'city', 'town', 'district', 'title']
]

,price_egp,property_type,area_value,bedrooms,bathrooms,city,town,district,title
497,"113,116.00",Apartment,155.00,3,3,Giza,6 October City,6 October Compounds,Finished Apartment155m+Garden for 113K per Qua...
85,"130,000.00",Duplex,233.00,3,3,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,duplex in zayed with 130K per quarter-unit 233 m
87,"130,000.00",Apartment,233.00,3,3,Giza,Sheikh Zayed City,Ivoire,duplex in zayed with 130K per quarter-unit 233 m
2139,"155,220.00",Apartment,200.00,3,3,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Pay 52K per month&Get Finished Apartment in Zayed
13056,"200,000.00",Chalet,1.00,2,2,Suez,Al Ain Al Sokhna,IL Monte Galala,Own Your BeachFront Unit On the Red Sea in Launch
223,"300,000.00",Chalet,120.00,2,2,Suez,Al Ain Al Sokhna,IL Monte Galala,"120m finished chalet ,Marina view300K per quarter"
11781,"300,000.00",Apartment,20.00,3,3,Cairo,New Cairo City,The 5th Settlement,APT RTM Full finished VIP view+locatin easy pa...
11836,"300,000.00",Apartment,20.00,3,3,Cairo,New Cairo City,The 5th Settlement,move in now 154m 3bed finished super lux VIP view
2792,"303,000.00",Apartment,20.00,3,3,Cairo,New Cairo City,The 5th Settlement,"Prime Home Projects in Beit El Watan, New Cairo -"
797,"325,000.00",Chalet,1.00,1,1,Suez,Al Ain Al Sokhna,IL Monte Galala,Studio on(sea+ycht marina+Galala mtns)360° fin...
476,"340,000.00",Apartment,106.00,2,3,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Apartment Finished+Acs in Zayed 340K Quarterly
1341,"345,500.00",Apartment,20.00,3,3,Cairo,New Cairo City,The 5th Settlement,Ground floor apartment with garden for sale at...
1193,"350,000.00",Apartment,20.00,2,2,Cairo,Mostakbal City - Future City,Mostakbal City Compounds,Green Square - Apartment 135 sq m -Special View
12782,"350,000.00",Chalet,20.00,studio,1,Suez,Al Ain Al Sokhna,IL Monte Galala,"Chalet for sale in Monte Galala, Ain Sokhna"
1449,"356,000.00",Apartment,20.00,3,2,Cairo,New Cairo City,The 5th Settlement,"Lowest price 147m down payment 175,000 install..."
1470,"356,000.00",Apartment,20.00,3,2,Cairo,New Cairo City,The 5th Settlement,"With a 5% down payment of only 178,000, you ca..."
1211,"356,100.00",Apartment,20.00,3,2,Cairo,New Cairo City,The 5th Settlement,Beit Al Watan-147 m- installments over 72 months
9316,"360,000.00",Apartment,20.00,2,2,Cairo,New Capital City,New Capital Compounds,RTM APt 116m Finished Central Park View 15Y in...
19503,"370,000.00",Apartment,20.00,1,1,Cairo,Mostakbal City - Future City,Mostakbal City Compounds,Apartment for sale at the lowest price in Bloo...
19512,"370,000.00",Apartment,20.00,1,1,Cairo,Mostakbal City - Future City,Mostakbal City Compounds,Apartment for sale at the lowest price in Bloo...

In [16]:
sell.nlargest(20, 'price_egp')[
    ['price_egp', 'property_type', 'area_value',
     'bedrooms', 'bathrooms', 'city', 'town', 'district', 'title']
]

,price_egp,property_type,area_value,bedrooms,bathrooms,city,town,district,title
3798,"1,000,000,000.00",Villa,238.00,3,7,North Coast,Ras Al Hekma,Jefaira,Standalone Priced Like a Chalet | Delivery 2026
6177,"988,888,888.00",Villa,"1,352.00",7,7+,Cairo,Zamalek,Mohamed Mazhar St.,مطلوب وفورا فيلا او قصر طراز معمارى لسفاره اور...
6179,"958,000,000.00",Villa,"1,255.00",6,6,Cairo,Zamalek,El Gezirah St.,مطلوب وفورا قصر او فيلا طراز معمارى لسفاره اور...
10350,"940,000,000.00",Land,"96,600.00",NaN,NaN,Giza,6 October City,Al Wahat Road,"Land for sale on the Oasis Road, 6th of October"
10358,"940,000,000.00",Land,"96,600.00",NaN,NaN,Giza,6 October City,Al Wahat Road,"Land for sale on the Oasis Road, 6th of October"
14187,"912,000,000.00",Whole Building,"4,000.00",7+,7+,Cairo,New Cairo City,The 5th Settlement,Last Building with Immediate Delivery OVER 10 ...
14188,"912,000,000.00",Whole Building,"4,000.00",7+,7+,Cairo,New Cairo City,The 5th Settlement,Last Building with Immediate Delivery OVER 10 ...
11135,"900,000,000.00",Palace,"4,800.00",7+,7+,Giza,6 October City,Cairo Alexandria Desert Road,Luxury palace with hotel finish for sale or rent
6256,"850,000,000.00",Land,"1,100.00",NaN,NaN,Cairo,Garden City,Nile Corniche St.,أرض للبيع بكورنيش النيل جاردن سيتي
11167,"844,000,000.00",Palace,"4,810.00",7+,7+,Giza,6 October City,Cairo Alexandria Desert Road,Luxury palace with hotel finish for sale or rent
11206,"770,400,000.00",Land,"38,520.00",NaN,NaN,Giza,Sheikh Zayed City,Riviera City,"Land for sale in Sheikh Zayed, Al Ghoul Street"
5249,"750,111,111.00",Villa,"1,647.00",7+,7+,Cairo,Garden City,Ahmed Basha St.,Urgently needed for European embassy palace villa
6395,"750,000,000.00",Villa,"1,801.00",5,6,Cairo,New Cairo City,El Katameya,K Heights | Fully Finished | All Types Available
9305,"750,000,000.00",Villa,"1,800.00",5,6,Cairo,New Cairo City,El Katameya,K Heights | Fully Finished | All Types Available
14208,"682,125,000.00",Apartment,159.00,3,3,Cairo,New Cairo City,The 5th Settlement,special 3 rooms appartmen at 5th settlment
14185,"670,000,000.00",Whole Building,"4,000.00",7+,7+,Cairo,New Cairo City,The 5th Settlement,Last Building with Immediate Delivery OVER 10 ...
3796,"650,000,000.00",Townhouse,138.00,3,4,North Coast,Ras Al Hekma,Jefaira,Villa Less Than Chalet Price - ready to move 2026
12387,"442,000,000.00",Villa,552.00,5,5,North Coast,Sidi Abdel Rahman,Marassi,5BR RTM Villa | Marassi Bay | 20% DP
12389,"442,000,000.00",Villa,552.00,5,5,North Coast,Sidi Abdel Rahman,Marassi,First Row Sea View Villa Marassi North Celia RTM
8762,"427,500,000.00",Villa,"1,000.00",5,7,Cairo,New Cairo City,El Katameya,Standalone for sale -1000m-First Row on the golf

In [17]:
sell.nlargest(20, 'area_value')[
    ['area_value', 'price_egp', 'property_type',
     'bedrooms', 'bathrooms', 'city', 'town', 'district', 'title']
]

,area_value,price_egp,property_type,bedrooms,bathrooms,city,town,district,title
10350,"96,600.00","940,000,000.00",Land,NaN,NaN,Giza,6 October City,Al Wahat Road,"Land for sale on the Oasis Road, 6th of October"
10358,"96,600.00","940,000,000.00",Land,NaN,NaN,Giza,6 October City,Al Wahat Road,"Land for sale on the Oasis Road, 6th of October"
10500,"42,000.00","400,000,000.00",Land,NaN,NaN,Giza,6 October City,Green Belt,Land for sale in New Sheikh Zayed
11206,"38,520.00","770,400,000.00",Land,NaN,NaN,Giza,Sheikh Zayed City,Riviera City,"Land for sale in Sheikh Zayed, Al Ghoul Street"
10419,"21,000.00","140,000,000.00",Land,NaN,NaN,Giza,6 October City,Green Belt,"Land for sale in the Green Belt, prime location"
10482,"21,000.00","140,000,000.00",Land,NaN,NaN,Giza,6 October City,Green Belt,"Land for sale in the Green Belt, prime location"
17634,"14,000.00","120,000,000.00",Land,NaN,NaN,Giza,6 October City,Green Belt,Land for sale in the Green Belt| prime Location
9842,"12,000.00","350,000,000.00",Land,NaN,NaN,Cairo,New Cairo City,The 5th Settlement,Land for Sale in The Third Settlement
5609,"10,600.00","265,000,000.00",Land,NaN,NaN,North Coast,Al Alamein,NaN,Prime Coastal Land Next to Siesta Marina
6021,"5,600.00","350,000,000.00",Hotel Apartment,7+,7+,Cairo,Downtown,Qasr El Nil,فندق خمس نجوم للبيع بوسط القاهرة
11167,"4,810.00","844,000,000.00",Palace,7+,7+,Giza,6 October City,Cairo Alexandria Desert Road,Luxury palace with hotel finish for sale or rent
11135,"4,800.00","900,000,000.00",Palace,7+,7+,Giza,6 October City,Cairo Alexandria Desert Road,Luxury palace with hotel finish for sale or rent
7745,"4,000.00","90,000,000.00",Land,NaN,NaN,Giza,6 October City,Green Belt,"Land 10 acres, 3 interfaces in very prime loca..."
14185,"4,000.00","670,000,000.00",Whole Building,7+,7+,Cairo,New Cairo City,The 5th Settlement,Last Building with Immediate Delivery OVER 10 ...
14187,"4,000.00","912,000,000.00",Whole Building,7+,7+,Cairo,New Cairo City,The 5th Settlement,Last Building with Immediate Delivery OVER 10 ...
14188,"4,000.00","912,000,000.00",Whole Building,7+,7+,Cairo,New Cairo City,The 5th Settlement,Last Building with Immediate Delivery OVER 10 ...
12961,"3,500.00","250,000,000.00",Villa,7+,7+,Cairo,New Cairo City,El Katameya,Ultra-Luxury Villa for Sale in Katameya Dunes
16002,"3,000.00","170,000,000.00",Villa,7+,7+,Cairo,New Cairo City,Al Rehab,The Largest and Most Exquisite Palace in Al Rehab
6198,"2,900.00","93,000,000.00",Whole Building,7+,7+,Cairo,Downtown,NaN,عمارة للبيع بوسط البلد شارع طلعت حرب
4321,"2,633.00","53,000,000.00",Whole Building,3,7+,Cairo,Garden City,Garden City St.,whole Building for sale in Garden City on Nile

In [18]:
sell.nsmallest(20, 'area_value')[
    ['area_value', 'price_egp', 'property_type',
     'bedrooms', 'bathrooms', 'city', 'town', 'district', 'title']
]

,area_value,price_egp,property_type,bedrooms,bathrooms,city,town,district,title
80,1.00,"610,000.00",Villa,4,4,Giza,Sheikh Zayed City,6th District,"luxury villa 229m + quarterly installment 610,000"
153,1.00,"582,800.00",Hotel Apartment,2,2,Cairo,Shorouk City,El Shorouk Compounds,Fully Finished 2BR Apartment in AL Shurouk City
154,1.00,"709,700.00",Hotel Apartment,3,3,Cairo,Shorouk City,El Shorouk Compounds,Fully Finished 3BR Apartment in AL Shurouk City
797,1.00,"325,000.00",Chalet,1,1,Suez,Al Ain Al Sokhna,IL Monte Galala,Studio on(sea+ycht marina+Galala mtns)360° fin...
7819,1.00,"610,000.00",Villa,4,4,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,"luxury villa 229m + quarterly installment 610,000"
7843,1.00,"610,000.00",Villa,4,4,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,"luxury villa 229m + quarterly installment 610,000"
7853,1.00,"610,000.00",Villa,4,4,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,"luxury villa 229m + quarterly installment 610,000"
7864,1.00,"610,000.00",Villa,4,4,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,"luxury villa 229m + quarterly installment 610,000"
7886,1.00,"610,000.00",Villa,4,4,Giza,Sheikh Zayed City,17th District,"luxury villa 229m + quarterly installment 610,000"
7914,1.00,"610,000.00",Villa,4,4,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,"luxury villa 229m + quarterly installment 610,000"
9201,1.00,"673,000.00",Hotel Apartment,1,1,Cairo,El Nozha,Sheraton Al Matar,Fully Finished Apartment Beside Almaza City Ce...
9277,1.00,"497,209.00",Penthouse,1,2,Cairo,New Cairo City,The 5th Settlement,Penthouse Apartment on Suez Road with 48% Disc...
9449,1.00,"1,350,000.00",Chalet,3,3,Suez,Al Ain Al Sokhna,La Vista,RTM 3BR Chalet with Sea & Pool View in Sokhna
9582,1.00,"4,100,000.00",Duplex,2,2,Cairo,New Cairo City,The 5th Settlement,Fully Finished Duplex Beside The AUC in Zed East
12219,1.00,"4,000,000.00",Chalet,2,2,North Coast,Ras Al Hekma,Jefaira,Prime finished chalet lagoon view in Jefaira
12222,1.00,"5,660,000.00",Villa,5,5,Giza,6 October City,Cairo Alexandria Desert Road,Prime villa for sale in Upville next to Palm H...
12712,1.00,"5,400,000.00",Twin House,4,4,Cairo,Shorouk City,El Shorouk Compounds,RTM Twin House in AL Shorouk by La Vista
13056,1.00,"200,000.00",Chalet,2,2,Suez,Al Ain Al Sokhna,IL Monte Galala,Own Your BeachFront Unit On the Red Sea in Launch
15468,1.00,"4,300,000.00",Penthouse,3,3,Cairo,New Cairo City,The 5th Settlement,RTM Penthouse in the Golden Square From La Vista
16327,1.00,"5,800,000.00",Villa,5,5,Giza,6 October City,Cairo Alexandria Desert Road,"Separate villa for sale in Upville ,Prime loca..."

In [19]:
rent.nlargest(20, 'price_egp')[
    ['price_egp', 'property_type', 'area_value',
     'bedrooms', 'bathrooms', 'city', 'town', 'district', 'title']
]

,price_egp,property_type,area_value,bedrooms,bathrooms,city,town,district,title
35356,"305,000,000.00",Villa,"1,150.00",4,4,Cairo,New Cairo City,The 5th Settlement,Finished villa in Lake View Compound for sale
33739,"185,000,000.00",Townhouse,260.00,4,5,Cairo,New Cairo City,South Investors Area,Town house for rent in la Terra furnished and ...
20818,"160,000,000.00",Villa,357.00,5,5,Giza,6 October City,Cairo Alexandria Desert Road,Villa for Rent | New Giza Compound-Fully Finis...
27617,"130,000,000.00",Townhouse,320.00,3,4,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,For Rent fully furnished townhouse at allegria
21275,"125,000,000.00",Townhouse,380.00,3,4,Giza,6 October City,Al Wahat Road,Luxurious Corner Town House in Golf Extension
26542,"90,000,000.00",Townhouse,250.00,4,4,Cairo,New Cairo City,Ext North Inves Area,Town House for sale in Dyar Park FF with AC's & K
37982,"70,000,000.00",Apartment,122.00,2,2,Cairo,New Cairo City,The 5th Settlement,Apartment For Rent Fully Furnished Prime location
28881,"60,000,000.00",Palace,"2,500.00",7,7+,North Coast,Sidi Abdel Rahman,Marassi,"Marassi Palace, first row on the sea, ultra super"
32815,"37,000,000.00",Villa,360.00,4,4,Cairo,New Cairo City,The 5th Settlement,Very prime location Villa Ready to move In PK2
37865,"28,113,558.00",Villa,800.00,4,5,Cairo,New Cairo City,Hyde Park,Stand alone villa for rent at hyde park new comp
20424,"25,000,000.00",Twin House,279.00,4,4,Giza,Sheikh Zayed City,6th District,Villa for sale - Greens Compound - Sheikh Zayed
32827,"24,600,000.00",Townhouse,257.00,4,4,Cairo,New Cairo City,The 5th Settlement,Very prime location town house best price in PK2
37860,"21,085,812.00",Twin House,290.00,5,5,Cairo,New Cairo City,Hyde Park,win villa for rent at Hyde Park Built up area 290
26706,"18,620,000.00",Penthouse,235.00,3,3,Cairo,New Cairo City,South Investors Area,Penthouse for Sale in Golden Square – Galleria...
36061,"17,000,000.00",Apartment,205.00,3,3,Cairo,New Cairo City,The 5th Settlement,distinct Apartment with Kitchen-ACs sale eastown
31626,"16,000,000.00",Apartment,211.00,3,3,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Zed Towers View on Sheikh Zayed nice view
23113,"15,890,000.00",Apartment,162.00,3,3,Cairo,New Cairo City,The 5th Settlement,Luxury Apartment in Sodic Villette 5th Settlement
23211,"15,000,000.00",Duplex,245.00,3,3,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Premium finishing – Prime location
38152,"15,000,000.00",Villa,400.00,3,3,Cairo,New Cairo City,The 5th Settlement,Standalone Villa for Rent in Stone Park Compound
27626,"14,500,000.00",Apartment,149.00,2,3,Cairo,New Cairo City,The 5th Settlement,Apartment with garden for sale in District 5

In [20]:
rent.nsmallest(20, 'price_egp')[
    ['price_egp', 'property_type', 'area_value',
     'bedrooms', 'bathrooms', 'city', 'town', 'district', 'title']
]

,price_egp,property_type,area_value,bedrooms,bathrooms,city,town,district,title
20565,"1,300.00",Apartment,157.00,2,3,Cairo,New Cairo City,The 5th Settlement,Apartment for rent in Lake View Residence – 2 bed
20587,"1,400.00",Villa,180.00,3,3,Cairo,New Cairo City,The 5th Settlement,Villa for rent 3bedroom in Mountain View i city
21056,"1,400.00",Apartment,210.00,3,3,Cairo,New Cairo City,The 5th Settlement,apartment 210m semi furnished rent eastown sodic
20586,"1,700.00",iVilla,278.00,4,3,Cairo,New Cairo City,The 5th Settlement,Apartment for rent 4bedroom in MV Hyde park
21646,"1,750.00",Apartment,170.00,2,4,Cairo,New Cairo City,North Investors Area,Apartment for rent 2bed in CFC
20563,"1,800.00",Apartment,268.00,3,3,Cairo,New Cairo City,The 5th Settlement,3-bedroom apartment for rent with kitchen &AC ...
20901,"2,000.00",Villa,355.00,5,5,Cairo,New Cairo City,The 5th Settlement,Premium Villa with private pool in Mivida
20445,"2,200.00",Apartment,400.00,3,3,Cairo,New Cairo City,El Katameya,Apartment Semi Furnished at katameya DUNES
20561,"2,200.00",Apartment,190.00,3,3,Cairo,New Cairo City,The 5th Settlement,3-bedroom apartment for rent fully Furniture LVR1
20719,"3,000.00",Apartment,70.00,3,1,Qalyubia,Shobra Al Khaimah,NaN,شقة مفروشة للايجار بشبرا الخيمة من المالك مباشرة
21112,"3,000.00",Apartment,96.00,2,2,Cairo,Madinaty,Privado,Luxury Furnished Apartment for Rent
20451,"4,444.00",Apartment,70.00,1,1,Cairo,Madinaty,NaN,Apartment for Rent in Madinaty – Ultra Modern
20682,"4,500.00",Apartment,80.00,2,1,Giza,6 October City,Al Wahat Road,شقة للإيجار فيو روعة كمباوند دجلة بالمز ٦ أكتوبر
20714,"4,800.00",Apartment,20.00,studio,1,Giza,6 October City,Al Hosary,للإيجار – ستوديو مفروش مميز في 6 أكتوبر الحي ا...
20441,"5,000.00",Apartment,90.00,2,1,Cairo,Nasr City,1st Zone,Furnished Hotel Apartments for Daily Monthly Rent
20442,"5,000.00",Apartment,100.00,2,1,Cairo,Nasr City,6th Zone,Furnished Hotel Apartments for Daily Rent Nasr...
20631,"5,500.00",Apartment,150.00,3,3,Cairo,Nasr City,6th Zone,شقه فندقيه VIP للايجار اليومي بكمبوند دلتا فلاورز
21922,"5,600.00",Apartment,35.00,studio,1,Giza,6 October City,3rd District,استوديو مفروش للايجار 6 اكتوبر الحي الاول مجاو...
21707,"6,000.00",Apartment,60.00,1,1,Cairo,Heliopolis - Masr El Gedida,Roxy,مكتب للايجار فى قلب ميدان روكسى مصر الجديده
21857,"6,000.00",Apartment,200.00,3,2,Cairo,Nasr City,Masaken Al Mohandesin,شقة فندقية امام سيتى استارز للايجار اليومي وال...

In [21]:
rent.nlargest(20, 'area_value')[
    ['area_value', 'price_egp', 'property_type',
     'bedrooms', 'bathrooms', 'city', 'town', 'district', 'title']
]

,area_value,price_egp,property_type,bedrooms,bathrooms,city,town,district,title
21043,"3,500.00","610,000.00",Villa,6,7+,Giza,Sheikh Zayed City,16th District,Luxury 6BR Villa with Pool & Garden – Karma Sh...
25866,"3,000.00","625,000.00",Villa,6,7+,Giza,Sheikh Zayed City,16th District,Luxury 6 Master Bedroom Hotel Villa - daily rent
27972,"3,000.00","500,000.00",Villa,7,7+,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,The most luxurious and elegant palace in Sheikh
27105,"2,700.00","386,000.00",Villa,5,7,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,5-Bedroom Hotel Villa – Shiekh Zayed | daily rent
26946,"2,500.00","700,000.00",Villa,7,7,Cairo,New Cairo City,El Katameya,luxury palace For ambassadors or busines men only
28881,"2,500.00","60,000,000.00",Palace,7,7+,North Coast,Sidi Abdel Rahman,Marassi,"Marassi Palace, first row on the sea, ultra super"
29154,"2,500.00","900,000.00",Villa,7,7+,Cairo,New Cairo City,El Katameya,1st Row Furnished villa for rent Katameya Heights
29172,"2,500.00","637,000.00",Villa,7+,7+,Cairo,New Cairo City,The 5th Settlement,Luxury standalone for rent 10bedrooms in lakeview
29742,"2,400.00","260,000.00",Villa,6,7+,Giza,Sheikh Zayed City,4th District,Mansion for Rent in El Karma 1 – Sheikh Zayed
36794,"2,400.00","275,000.00",Villa,7,7+,Giza,Sheikh Zayed City,4th District,Palace for rent in Al Karma 1 - Sheikh Zayed
20242,"2,000.00","576,000.00",Villa,7,7+,Cairo,New Cairo City,El Katameya,Elite Furnished Villa for Rent in Katameya Dunes
29149,"2,000.00","650,000.00",Villa,4,5,Cairo,New Cairo City,The 5th Settlement,Palms Hills PK1 Luxury Villa forrent in New Cairo
29164,"2,000.00","800,000.00",Villa,7+,7+,Cairo,New Cairo City,El Katameya,VIP Palace for rent a private pool KATAMEYA DUNES
29179,"2,000.00","833,000.00",Villa,6,7,Cairo,New Cairo City,El Katameya,Fully furnished imported furniture katameya hi...
33545,"2,000.00","750,000.00",Palace,7+,7+,Cairo,New Cairo City,The 5th Settlement,Luxurious Fully Furnished Palace Rent in Diplo...
36535,"2,000.00","350,000.00",Villa,7+,7+,Cairo,New Cairo City,El Katameya,Private Pool Villa for rent in Katameya Dunes
30942,"1,920.00","850,000.00",Whole Building,7+,7+,Giza,Mohandessin,Ahmed Orabi St.,"Mixed-Use Building for Rent – Ahmed Orabi St.,"
29181,"1,800.00","650,000.00",Villa,6,7,Cairo,New Cairo City,El Katameya,Katameya Dunes Golf & Lake View Elite Villa Rent
31130,"1,800.00","410,000.00",Villa,7,7+,Giza,6 October City,Cairo Alexandria Desert Road,7BR luxury villa pool Palm Hills SZ daily rent
20131,"1,700.00","500,000.00",Villa,7+,6,Cairo,New Cairo City,El Katameya,katameya dunes-For Rent Standalone 1700m View ...

In [22]:
rent.nsmallest(20, 'area_value')[
    ['area_value', 'price_egp', 'property_type',
     'bedrooms', 'bathrooms', 'city', 'town', 'district', 'title']
]

,area_value,price_egp,property_type,bedrooms,bathrooms,city,town,district,title
27032,1.00,"85,000.00",iVilla,3,3,Cairo,New Cairo City,The 5th Settlement,Ivilla with Apt. Price! for immediate Rent Cal...
32342,6.00,"170,000.00",Villa,4,3,Cairo,New Cairo City,Hyde Park,Standalone Villa for Rent in Hyde Park
20714,20.00,"4,800.00",Apartment,studio,1,Giza,6 October City,Al Hosary,للإيجار – ستوديو مفروش مميز في 6 أكتوبر الحي ا...
30542,20.00,"18,000.00",Apartment,1,1,Cairo,New Cairo City,El Lotus,Furnished Studio for Rent in El Lotus - New Cairo
36330,20.00,"45,000.00",Apartment,studio,1,Cairo,New Cairo City,El Lotus,"Apartment for rent in Fifth Settlement, South ..."
24554,25.00,"28,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,17th District,Studio apartment in Courtyard Beverly Hills
24563,25.00,"25,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,17th District,Studio apartment for rent in Westown Beverly H...
25371,25.00,"30,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Furnished studio for rent in Westown - sodic
26503,25.00,"15,000.00",Apartment,1,1,Cairo,New Cairo City,El Lotus,"Hotel Room – South Lotus, New Cairo"
29803,25.00,"25,999.00",Apartment,studio,1,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,UltraSuperLux Furnished UltraModern Landscape ...
30599,25.00,"20,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,6th District,Semi-furnished Studio with roof in Zayed Regency
30604,25.00,"20,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Semi-furnished Studio with roof in Zayed Regency
31096,25.00,"25,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Fully Furnished Studio For Rent Westown Sodic
34598,25.00,"20,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Studio for rent in Zayed Regency
35573,25.00,"31,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,17th District,Furnished studio apartment for rent in Westown
36924,25.00,"25,000.00",Apartment,studio,1,Cairo,New Cairo City,El Lotus,"Apartment for rent in Fifth Settlement, South ..."
37161,25.00,"25,000.00",Apartment,studio,1,Cairo,New Cairo City,El Lotus,"Studio apartment for rent in Fifth Settlement,..."
39124,25.00,"25,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Furnished Studio Apartment for Rent in Westown
31878,26.00,"17,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Studio with kitchen and acs in Westown Sodic
31882,26.00,"22,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Furnished studio in Westown sodic

## **bedrooms & bathrooms breaking down**

In [23]:
re['bedrooms'].value_counts(dropna=False)

bedrooms
3         18189
2          9418
4          6121
5          2128
1          1616
studio     1125
6           670
7           227
7+          184
NaN          35
Name: count, dtype: int64

In [24]:
re['bathrooms'].value_counts(dropna=False)

bathrooms
3       14168
2       11037
4        6135
1        4452
5        2449
6         794
7         380
7+        260
NaN        30
none        8
Name: count, dtype: int64

In [25]:
#Check the relationship between sale/rent and price period
pd.crosstab(
    re['category'],
    re['price_period'],
    margins=True
)

price_period  monthly   sell    All
category
buy                 0  19802  19802
rent            19910      0  19910
All             19910  19802  39712

## **Duplicated rows**

In [26]:
re.duplicated().sum()

np.int64(0)

In [27]:
re['listing_id'].duplicated().sum()

np.int64(0)

No duplicate listing IDs does NOT mean no duplicate properties/listings.

It means only that the IDs are unique.

##**creating 2 dataframes**

In [28]:
sell # 19803 rows

,listing_id,internal_id,category,listing_type,detail_url,property_type,offering_type,completion_status,title,price_egp,price_period,price_currency,location_full,city,town,district,subdistrict,lat,lon,bedrooms,bathrooms,area_value,area_unit,furnished,listing_level,is_premium,is_verified,is_featured,is_new_construction,is_direct_from_dev,is_exclusive,listed_date,images_count,has_view_360,video_url,reference,rera,description,amenities,payment_method,agent_id,agent_name,agent_email,agent_is_super,agent_languages,broker_id,broker_name,broker_email,broker_phone,contact_phone,contact_whatsapp,contact_email,scraped_at
0,F7QB31CGWE509V2W7DF2GARB2C,"56,009,081.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/duple...,Duplex,Residential for Sale,completed,Garden Villa - Lake View Boutique - Prime Loca...,"24,500,000.00",sell,EGP,"The Lakeview Boutique Villas, 5th Settlement C...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.04,31.53,3,6,445.00,sqm,NaN,premium,True,False,False,False,False,False,2026-03-03T19:15:06Z,6,False,NaN,F7QB31CGWE509V2W7DF2GARB2C,NaN,Garden Villa for Sale – Featured in Lake View ...,Balcony | Built in Wardrobes | Covered Parking...,cash,"58,866.00",pierre osama,pierre.Osama@spade-consultancy.com,False,NaN,"5,758.00",Spade consultancy,mohmedg.sedik@gmail.com,"1,001,436,511.00","201,201,801,443.00","20,221,257,340.00",pierre.Osama@spade-consultancy.com,2026-03-04T14:20:33.281007
1,K1JC3D6N57ED52N3VX1QQKHHXG,"56,247,925.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,off_plan,For Sale: Finished Apartment+ ACs in Village West,"5,145,000.00",sell,EGP,"Village West, Sheikh Zayed Compounds, Sheikh Z...",Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Village West,30.05,31.02,2,2,123.00,sqm,PARTLY,premium,True,False,False,False,False,False,2026-03-04T11:24:23Z,10,False,NaN,rb304,NaN,For Sale: Finished Apartment with ACs in Villa...,Balcony | Built in Wardrobes | Central A/C | C...,cash,"67,166.00",Rana Bahaa ElDeen,ranoushamer901@gmail.com,False,NaN,492.00,Abrag Real Estate,snawara71@gmail.com,"201,001,188,088.00","201,007,169,666.00","20,221,257,340.00",ranoushamer901@gmail.com,2026-03-04T14:20:33.281007
2,Q6GEB8T6PZTJGNNPWA5PX3JCWR,"56,253,883.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,UnderMarket Price for Apt. 250 RTM PrimeLocation,"10,800,000.00",sell,EGP,"Palm Hills New Cairo, 5th Settlement Compounds...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.01,31.58,4,4,250.00,sqm,NaN,premium,True,False,False,False,False,False,2026-03-04T14:03:51Z,13,False,NaN,250pncash,NaN,Palm Hills New Cairo Apartment BUA: 250sqm 4 B...,Balcony | Built in Wardrobes | Central A/C | C...,cash,"47,158.00",Ashraf Shaaban,ashrafsobhy99@hotmail.com,False,English | Arabic,"5,279.00",Premises,mahmouddessam@hotmail.com,"201,005,133,389.00","201,090,963,241.00","20,221,257,340.00",ashrafsobhy99@hotmail.com,2026-03-04T14:20:33.281007
3,PPH0852SAB266X6GSVATJP4F0M,"56,250,852.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,lowest price 2bds fullyfurnished @ lake view,"10,500,000.00",sell,EGP,"Lake View Residence, 5th Settlement Compounds,...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.03,31.54,2,2,136.00,sqm,YES,premium,True,False,False,False,False,False,2026-03-04T12:38:11Z,11,False,NaN,PPH0852SAB266X6GSVATJP4F0M,NaN,Lake View Residence 136 sqm Fully Finished Ren...,Balcony | Built in Wardrobes | Central A/C | C...,cash,"63,401.00",ebrahim hossam,ebrahim.hossam@spade-consultancy.com,False,NaN,"5,758.00",Spade consultancy,mohmedg.sedik@gmail.com,"1,001,436,511.00","201,070,115,211.00","20,221,257,340.00",ebrahim.hossam@spade-consultancy.com,2026-03-04T14:20:33.281007
4,QCSA4TNDEBBV7BNY8ANST3TB50,"55,995,764.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/villa...,Villa,Residential for Sale,completed,Exclusive Type M with Lowest Price RTM in PNC,"19,500,000.00",sell,EGP,"Palm Hills New Cairo, 5th Settlement Compounds...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.01,31.58,4,4,255.00,sqm,NaN,premium,True,False,False,False,False,False,2026-03-03T09:45:41Z,17,False,NaN,VillTyM,NaN,Palm Hills New Cairo Type M BUA: 255sqm LAND: ...,Balcony | Built in Wardrobes | Central A/C | C...,cash,"47,158.00",Ashraf Shaaban,ashrafsobhy99@hotmail.com,False,English | Arabic,"5,279.00",Premises,mahmouddessam@hotmail.com,"201,005,133,389.00","201,090,963,241.00","20,221,257,340.00",ashrafsobhy99@hotmail.com,2026-03-04T14:20:33.281007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19798,89MT8GABBWXVFPGJETKXYG2GPW,"55,004,293.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,Ground floor apartment with private garden for...,"7,000,000.00",sell,EGP,"Privado, Madinaty, Cairo",Cairo,Madinaty,Privado,NaN,30.09,31.67,3,2,125.00,sqm,NO,standard,False,False,False,False,False,False,2026-02-27T12:52:18Z,17,False,NaN,770,NaN,Ground floor apartment with private garden for...,Balcony | Private Garden | Shared Spa | Shared...,cash,"69,259.00",Menna Alaa,mennaalaa7267@gmail.com,False,English | Arabic,"6,229.00",Rikaz,boba.moh1981@gmail.com,"1,208,233,373.00","201,222,254,578.00","20,221,257,340.00",mennaalaa7267@gmail.com,2026-03-04T16:22:41.610135
19799,YGWE729FPHF1S12D1GY3Y7C3EM,"55,004,288.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/chale...,Chalet,Residential for Sale,off_plan_primary,Chalet 2 BR With Prime View Cash Discount 50%,"1,666,000.00",sell,EGP,"Golf Porto Marina, Al Alamein, North Coast",North Coast,Al Alamein,Golf Porto Marina,NaN,30.84,28.92,2,1,60.00,sqm,NaN,standard,False,False,False,False,False,False,2026-02-27T12:52:11Z,12,False,NaN,hamsagolf285,NaN,Golf Porto Marina Chalet For Sale Very Prime L...,Balcony | Covered Parking | Shared Pool | Secu...,cash,"70,412.00",Nada azzeldain,Nada.azzeldain@gmail.com,False,NaN,"4,650.00",Towers Map,info@towersmap.com,"201,066,699,903.00","201,554,047,782.00","201,554,047,782.00",Nada.azzeldain@gmail.com,2026-03-04T16:22:41.610135
19800,1C01HWHGPZKQSJW1TF3MW0EZFW,"55,004,285.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/twin-...,Twin House,Residential for Sale,completed_primary,278m Villa Ready to View in Palm Hills Plateau,"7,000,000.00",sell,EGP,"Tawny Hyde Park, 6 October Compounds, 6 Octobe...",Giza,6 October City,6 October Compounds,Tawny Hyde Park,29.96,30.92,3,4,50.00,sqm,NaN,standard,False,False,False,False,False,False,2026-02-27T12:51:37Z,22,False,NaN,1C01HWHGPZKQSJW1TF3MW0EZFW,NaN,Own Your Villa Immediately in the Prime Area o...,Balcony | Built in Wardrobes | Central A/C | C...,cash | installments,"67,568.00",Youssef Ezzat,youssefkhalifa1920@gmail.com,False,NaN,"6,126.00",بروبيرتي هيلز ون,afarouk309@gmail.com,"201,228,173,413.00","201,034,485,985.00","20,221,257,340.00",youssefkhalifa1920@gmail.com,2026-03-04T16:22:41.610135
19801,BQ5FX8XXAENEDTVRQNT05YTCKM,"55,004,282.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/villa...,Villa,Residential for Sale,completed_primary,"288sqm Villa Palm Hills, Immediate, 8-Year Plan","7,200,000.00",sell,EGP,"Tawny Hyde Park, 6 October Compounds, 6 Octobe...",Giza,6 October City,6 October Compounds,Tawny Hyde Park,29.96,30.92,3,4,20.00,sqm,NaN,standard,False,False,False,False,False,False,2026-02-27T12:51:02Z,21,False,NaN,BQ5FX8XXAENEDTVRQNT05YTCKM,NaN,Own Your Standalone Villa Immediately in the P...,Balcony | Built in Wardrobes | Central A/C | C...,cash | installments,"67,568.00",Youssef Ezzat,youssefkhalifa1920@gmail.com,False,NaN,"6,126.00",بروبيرتي هيلز ون,afarouk309@gmail.com,"201,228,173,413.00","201,034,485,985.00","20,221,257,340.00",youssefkhalifa1920@gmail.com,2026-03-04T16:22:41.610135
19802,QHENWSRQYFNR044CCN6ZNYY918,"55,004,268.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,Finished apartment for sale in Eastown Sodic,"12,700,000.00",sell,EGP,"Eastown, 5th Settlement Compounds, The 5th Set...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.01,31.52,3,3,156.00,sqm,NO,standard,False,False,False,False,False,False,2026-02-27T12:50:53Z,7,False,NaN,eAST156S,NaN,Below Market Price Apartment for Sale in Easto...,Balcony | Covered Parking | Security,cash,"48,304.00",FORTUNE REALTY,fourtunerealityeg@gmail.com,False,English | Arabic,"5,373.00",Fortune Real Estate,fourtunerealityeg@gmail.com,"1,101,110,063.00","201,103,338,912.00","20,221,257,340.00",fourtunerealityeg@gmail.com,2026-03-04T16:22:41.610135

In [29]:
rent #19910 rows

,listing_id,internal_id,category,listing_type,detail_url,property_type,offering_type,completion_status,title,price_egp,price_period,price_currency,location_full,city,town,district,subdistrict,lat,lon,bedrooms,bathrooms,area_value,area_unit,furnished,listing_level,is_premium,is_verified,is_featured,is_new_construction,is_direct_from_dev,is_exclusive,listed_date,images_count,has_view_360,video_url,reference,rera,description,amenities,payment_method,agent_id,agent_name,agent_email,agent_is_super,agent_languages,broker_id,broker_name,broker_email,broker_phone,contact_phone,contact_whatsapp,contact_email,scraped_at
19803,N7B2CXT5B7AA2QFEM3CEPZE36W,"56,264,047.00",rent,property,https://www.propertyfinder.eg/en/plp/rent/apar...,Apartment,Residential for Rent,NaN,First use semi furnished 2BR in El Patio Oro,"35,000.00",monthly,EGP,"El Patio Oro, 5th Settlement Compounds, The 5t...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.03,31.59,2,2,128.00,sqm,PARTLY,premium,True,False,False,False,False,False,2026-03-04T21:13:08Z,9,False,NaN,TR_PT,NaN,Apartment with kitchen and air conditioning fo...,Balcony | Central A/C | Covered Parking | Shar...,NaN,"55,901.00",Nouran nabil,nourannabil811@gmail.com,False,NaN,"5,389.00",Trust,youssef_eldabaa1998@icloud.com,"201,146,612,464.00","201,013,484,757.00","20,221,257,340.00",nourannabil811@gmail.com,2026-03-04T21:42:33.053032
19804,ZR1FDX0HR9NRW5RYT753M1HJYM,"56,251,323.00",rent,property,https://www.propertyfinder.eg/en/plp/rent/apar...,Apartment,Residential for Rent,NaN,"Unfurnished apartment for rent with kitchen, a...","50,000.00",monthly,EGP,"Al Imam Zain Al Abdeen St., El Banafseg 9, El ...",Cairo,New Cairo City,El Banafseg,El Banafseg 9,30.05,31.47,3,3,300.00,sqm,NO,premium,True,False,False,False,False,False,2026-03-04T12:47:53Z,20,False,NaN,E14755,NaN,E14755 Unfurnished apartment for rent with kit...,Balcony | Security,NaN,"66,449.00",ابتسام اسامة ادمن,almazreal25@gmail.com,False,NaN,"2,520.00",Al Maz Real Estate,tmamsayed162@gmail.com,"201,016,164,162.00","201,104,889,528.00","20,221,257,340.00",almazreal25@gmail.com,2026-03-04T21:42:33.135955
19805,SAZ0ESNJBAMXTGWFZXXNTVG4Y4,"56,247,375.00",rent,property,https://www.propertyfinder.eg/en/plp/rent/apar...,Apartment,Residential for Rent,NaN,Furnished apartment for rent in Al Yasmin 2 Vi...,"45,000.00",monthly,EGP,"El Yasmeen 2, El Yasmeen, New Cairo City, Cairo",Cairo,New Cairo City,El Yasmeen,El Yasmeen 2,30.05,31.45,3,3,210.00,sqm,YES,premium,True,False,False,False,False,False,2026-03-04T11:12:17Z,6,False,NaN,E14748,NaN,E14748 Furnished apartment for rent in Al Yasm...,Balcony | Security,NaN,"66,449.00",ابتسام اسامة ادمن,almazreal25@gmail.com,False,NaN,"2,520.00",Al Maz Real Estate,tmamsayed162@gmail.com,"201,016,164,162.00","201,104,889,528.00","20,221,257,340.00",almazreal25@gmail.com,2026-03-04T21:42:33.135955
19806,35YS1VD1EQFGXQSNXARWM5P3W8,"56,246,747.00",rent,property,https://www.propertyfinder.eg/en/plp/rent/apar...,Apartment,Residential for Rent,NaN,Unfurnished apartment for rent with air condit...,"25,000.00",monthly,EGP,"Mohamed Naguib Axis, Abou El Houl, New Cairo C...",Cairo,New Cairo City,Abou El Houl,Mohamed Naguib Axis,29.98,31.47,2,2,150.00,sqm,NO,premium,True,False,False,False,False,False,2026-03-04T10:58:28Z,15,False,NaN,E14745,NaN,E14745 Unfurnished apartment for rent with air...,Balcony | Security,NaN,"50,635.00",نورا الماظ,almazmaysa@gmail.com,False,NaN,"2,520.00",Al Maz Real Estate,tmamsayed162@gmail.com,"201,016,164,162.00","201,145,451,743.00","20,221,257,340.00",almazmaysa@gmail.com,2026-03-04T21:42:33.135955
19807,039Z8VKMPKYYJ5J4TW6Y2AS6SC,"56,241,813.00",rent,property,https://www.propertyfinder.eg/en/plp/rent/apar...,Apartment,Residential for Rent,NaN,Furnished apartment for rent behind Mirage Cit...,"40,000.00",monthly,EGP,"Mostafa Kamel Axis, The 1st Settlement, New Ca...",Cairo,New Cairo City,The 1st Settlement,Mostafa Kamel Axis,30.05,31.44,2,2,130.00,sqm,YES,premium,True,False,False,False,False,False,2026-03-04T09:19:33Z,7,False,NaN,E12494B,NaN,E12494B Furnished apartment for rent behind Mi...,Balcony | Security,NaN,"44,158.00",منا جمعة,nourabdelhalem7@gmail.com,False,NaN,"2,520.00",Al Maz Real Estate,tmamsayed162@gmail.com,"201,016,164,162.00","201,066,013,728.00","20,221,257,340.00",nourabdelhalem7@gmail.com,2026-03-04T21:42:33.136969
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39708,YQT77A2J44CPMV7H28J9V30ADR,"8,667,639.00",rent,property,https://www.propertyfinder.eg/en/plp/rent/apar...,Apartment,Residential for Rent,NaN,"Furnished apartment for rent in Al Rehab, 250M","55,000.00",monthly,EGP,"El Rehab Extension, Al Rehab, New Cairo City, ...",Cairo,New Cairo City,Al Rehab,El Rehab Extension,30.06,31.51,3,3,250.00,sqm,YES,standard,False,False,False,False,False,False,2026-02-07T16:33:32Z,7,False,NaN,CVU146900,NaN,Furnished apartment for rent in Al Rehab Phase...,Balcony | Central A/C | Kitchen Appliances | S...,NaN,"68,162.00",Atia Saad,atiasaad188@gmail.com,False,NaN,"4,456.00",Escan Group,aahmdymagdy201070@gmail.com,"201,123,293,822.00","201,103,971,260.00","20,221,257,340.00",atiasaad188@gmail.com,2026-03-05T00:43:04.172513
39709,8385GKAA00BXE8FYPWNQ29VF3M,"8,667,632.00",rent,property,https://www.propertyfinder.eg/en/plp/rent/apar...,Apartment,Residential for Rent,NaN,FULLY FURNISHED apartment for RENT 3 Bedroom,"45,000.00",monthly,EGP,"City View, Cairo Alexandria Desert Road, 6 Oct...",Giza,6 October City,Cairo Alexandria Desert Road,City View,30.01,31.09,3,3,180.00,sqm,YES,standard,False,False,False,False,False,False,2026-02-07T16:32:23Z,16,False,NaN,8385GKAA00BXE8FYPWNQ29VF3M,NaN,"AVAILABLE MID AUGUST, 2025 An Elegant 3 Bedroo...",Balcony | Built in Wardrobes | Central A/C | C...,NaN,"23,636.00",Julia Hassan,yuliya.hassan@remax.com.eg,False,NaN,430.00,RE/MAX Al Mohager,m.degheady@remax.com.eg,"201,030,831,507.00","201,094,675,896.00","20,221,257,340.00",yuliya.hassan@remax.com.eg,2026-03-05T00:43:04.172513
39710,R9PTSC3V5RZ77ZT9X69TBE1PEC,"8,667,625.00",rent,property,https://www.propertyfinder.eg/en/plp/rent/town...,Townhouse,Residential for Rent,NaN,Furnished villa for rent in Town 5 rooms near New,"120,000.00",monthly,EGP,"Joulz, Cairo Alexandria Desert Road, 6 October...",Giza,6 October City,Cairo Alexandria Desert Road,Joulz,30.01,31.04,5,5,320.00,sqm,YES,standard,False,False,False,False,False,False,2026-02-07T16:31:32Z,11,False,NaN,R9PTSC3V5RZ77ZT9X69TBE1PEC,NaN,Furnished villa for rent at a special price To...,Balcony | Central A/C | Covered Parking | Kitc...,NaN,"16,061.00",Mahmoud El abbassy,Mahmoudalabasy94@gmail.com,False,NaN,"4,679.00",Abrag 2,NaN,NaN,"201,114,587,365.00","20,221,257,340.00",Mahmoudalabasy94@gmail.com,2026-03-05T00:43:04.172513
39711,9Q295E8B6ET3V30Z31925BR6ZG,"8,667,615.00",rent,property,https://www.propertyfinder.eg/en/plp/rent/apar...,Apartment,Residential for Rent,NaN,For Rent – Premium 196m² Fully Finished Apartment,"50,000.00",monthly,EGP,"New Giza, Cairo Alexandria Desert Road, 6 Octo...",Giza,6 October City,Cairo Alexandria Desert Road,New Giza,30.01,31.06,2,2,196.00,sqm,NO,standard,False,False,False,False,False,False,2026-02-07T16:29:24Z,6,False,NaN,9Q295E8B6ET3V30Z31925BR6ZG,NaN,For Rent – Premium 196m² Fully Finished Apartm...,Balcony | Kitchen Appliances | Covered Parking...,NaN,"60,109.00",Yasmin Helmy,yalashwat2000@gmail.com,False,NaN,430.00,RE/MAX Al Mohager,m.degheady@remax.com.eg,"201,030,831,507.00","201,070,720,366.00","20,221,257,340.00",yalashwat2000@gmail.com,2026-03-05T00:43:04.172513
39712,HYEPN5XPWQT7K05K4ST7EDWW5R,"8,667,602.00",rent,property,https://www.propertyfinder.eg/en/plp/rent/apar...,Apartment,Residential for Rent,NaN,If you're looking hotel units contact us now,"75,000.00",monthly,EGP,"Villette, 5th Settlement Compounds, The 5th Se...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.02,31.55,2,2,144.00,sqm,YES,standard,False,False,False,False,False,False,2026-02-07T16:26:50Z,10,False,NaN,HYEPN5XPWQT7K05K4ST7EDWW5R,NaN,Unit Description: Location: Villette Compound ...,Balcony | Built in Wardrobes | Central A/C | C...,NaN,"56,917.00",Fatma hesham,sh2927333@gmail.com,False,English | Arabic,"5,307.00",Smart Home,ahmedbompo9@gmail.com,"201,011,981,802.00","201,040,817,294.00","20,221,257,340.00",sh2927333@gmail.com,2026-03-05T00:43:04.172513

## **Cleaning**

In [30]:
# **drop meaningless columns**
sell.drop(columns=['price_period'],inplace=True,errors='ignor')# one value:sell
rent.drop(columns=['price_period'], inplace=True, errors='ignore')# one value:monthly

sell.drop(columns=['offering_type'],inplace=True,errors='ignore')# one value:Residential for Sale
rent.drop(columns=['offering_type'],inplace=True,errors='ignore')# one value:Residential for rent

sell.drop(columns=['category'],inplace=True,errors='ignore')# one value:buy
rent.drop(columns=['category'],inplace=True,errors='ignore')# one value:rent

sell.drop(columns=['rera'],inplace=True,errors='ignore')#NULL
rent.drop(columns=['rera'],inplace=True,errors='ignore')#NULL

## **doubted commands**

In [31]:
columns_to_keep = [###########
    
    'property_type',
   
    'completion_status',
    
    'price_egp',
    
    'city',
    'town',
    'district',
    'lat',
    'lon',
    'bedrooms',
    'bathrooms',
    'area_value',
    'furnished',
    'listing_level',
    'is_premium',
    'is_featured',
    'listed_date',
    'payment_method',
    'agent_id',
    'broker_id',
]
sell=sell[columns_to_keep]
rent=rent[columns_to_keep]

In [32]:
(sell['area_value'] == 1).sum()

np.int64(23)

In [33]:
(rent['area_value'] == 1).sum()

np.int64(1)

In [34]:
for dataframe in [rent, sell]:
  
  dataframe['listed_date'] = pd.to_datetime(dataframe['listed_date'])

  # Ensure agent_id and broker_id are treated as categorical/string IDs
  dataframe['agent_id'] = (
      dataframe['agent_id'].fillna(-1).astype(int).astype(str)
  )
  dataframe['broker_id'] = (
      dataframe['broker_id'].fillna(-1).astype(int).astype(str)
  )

In [35]:
print(f"Rent dupliccated: {rent.duplicated().sum()}")
print(f"Sell dupliccated: {sell.duplicated().sum()}")

Rent dupliccated: 8
Sell dupliccated: 28

In [36]:
rent.drop_duplicates(inplace=True)
sell.drop_duplicates(inplace=True)

In [37]:
#Filling the completion_status in the rent ste
rent['completion_status'] = rent['completion_status'].fillna('completed')

In [38]:
sell.info()

<class 'pandas.DataFrame'>
Index: 19775 entries, 0 to 19802
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   property_type      19774 non-null  str
 1   completion_status  19735 non-null  str
 2   price_egp          19774 non-null  float64
 3   city               19774 non-null  str
 4   town               19774 non-null  str
 5   district           19555 non-null  str
 6   lat                19774 non-null  float64
 7   lon                19774 non-null  float64
 8   bedrooms           19743 non-null  str
 9   bathrooms          19745 non-null  str
 10  area_value         19774 non-null  float64
 11  furnished          11536 non-null  str
 12  listing_level      19774 non-null  str
 13  is_premium         19775 non-null  bool
 14  is_featured        19775 non-null  bool
 15  listed_date        19774 non-null  datetime64[us, UTC]
 16  payment_method     19774 non-null  str
 17  agent_id           19775 non-null  str
 18  broker_id          19775 non-null  str
dtypes: bool(2), datetime64[us, UTC](1), float64(4), str(12)
memory usage: 4.4 MB

In [39]:
rent.info()

<class 'pandas.DataFrame'>
Index: 19902 entries, 19803 to 39712
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   property_type      19902 non-null  str
 1   completion_status  19902 non-null  str
 2   price_egp          19902 non-null  float64
 3   city               19902 non-null  str
 4   town               19902 non-null  str
 5   district           19775 non-null  str
 6   lat                19902 non-null  float64
 7   lon                19902 non-null  float64
 8   bedrooms           19899 non-null  str
 9   bathrooms          19902 non-null  str
 10  area_value         19902 non-null  float64
 11  furnished          19757 non-null  str
 12  listing_level      19902 non-null  str
 13  is_premium         19902 non-null  bool
 14  is_featured        19902 non-null  bool
 15  listed_date        19902 non-null  datetime64[us, UTC]
 16  payment_method     137 non-null    str
 17  agent_id           19902 non-null  str
 18  broker_id          19902 non-null  str
dtypes: bool(2), datetime64[us, UTC](1), float64(4), str(12)
memory usage: 4.2 MB

In [40]:
sell['bathrooms'].unique()

<ArrowStringArray>
['6', '2', '4', nan, '1', '3', '7+', '5', '7', 'none']
Length: 10, dtype: str

In [41]:
# Filter out unrealistic placeholder areas (< 20 sqm)
sell = sell[sell['area_value'] >= 20].copy()
rent = rent[rent['area_value'] >= 20].copy()

In [42]:
#Making bedrooms and bathrooms  Ordered Categorical

bed_order = ['studio', '1', '2', '3', '4', '5', '6', '7', '7+']
bath_order = ['none', '1', '2', '3', '4', '5', '6', '7', '7+']

for df in [sell, rent]:
    df['bedrooms'] = pd.Categorical(df['bedrooms'], categories=bed_order, ordered=True)
    df['bathrooms'] = pd.Categorical(df['bathrooms'], categories=bath_order, ordered=True)

In [43]:
sell = sell.dropna(subset=['price_egp']).copy()

In [44]:
sell['price_per_sqm'] = sell['price_egp'] / sell['area_value']
sell['price_per_sqm']

0        55,056.18
1        41,829.27
2        43,200.00
3        77,205.88
4        76,470.59
           ...
19798    56,000.00
19799    27,766.67
19800   140,000.00
19801   360,000.00
19802    81,410.26
Name: price_per_sqm, Length: 19692, dtype: float64

In [45]:
# In sell: fill NaN with 'NO'
sell['furnished'] = sell['furnished'].fillna('NO')

# In rent: fill NaN with mode or 'Unknown'
rent['furnished'] = rent['furnished'].fillna('YES')

In [46]:
sell['district'] = sell['district'].fillna(sell['town'])
rent['district'] = rent['district'].fillna(rent['town'])

In [47]:
rent['price_per_sqm'] = rent['price_egp'] / rent['area_value']

In [51]:
re[re['area_value']>=20]
pd.set_option('display.max_columns',53)

In [53]:
re[re['area_value']>=20].head(50)

,listing_id,internal_id,category,listing_type,detail_url,property_type,offering_type,completion_status,title,price_egp,price_period,price_currency,location_full,city,town,district,subdistrict,lat,lon,bedrooms,bathrooms,area_value,area_unit,furnished,listing_level,is_premium,is_verified,is_featured,is_new_construction,is_direct_from_dev,is_exclusive,listed_date,images_count,has_view_360,video_url,reference,rera,description,amenities,payment_method,agent_id,agent_name,agent_email,agent_is_super,agent_languages,broker_id,broker_name,broker_email,broker_phone,contact_phone,contact_whatsapp,contact_email,scraped_at
0,F7QB31CGWE509V2W7DF2GARB2C,"56,009,081.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/duple...,Duplex,Residential for Sale,completed,Garden Villa - Lake View Boutique - Prime Loca...,"24,500,000.00",sell,EGP,"The Lakeview Boutique Villas, 5th Settlement C...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.04,31.53,3,6,445.00,sqm,NaN,premium,True,False,False,False,False,False,2026-03-03T19:15:06Z,6,False,NaN,F7QB31CGWE509V2W7DF2GARB2C,NaN,Garden Villa for Sale – Featured in Lake View ...,Balcony | Built in Wardrobes | Covered Parking...,cash,"58,866.00",pierre osama,pierre.Osama@spade-consultancy.com,False,NaN,"5,758.00",Spade consultancy,mohmedg.sedik@gmail.com,"1,001,436,511.00","201,201,801,443.00","20,221,257,340.00",pierre.Osama@spade-consultancy.com,2026-03-04T14:20:33.281007
1,K1JC3D6N57ED52N3VX1QQKHHXG,"56,247,925.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,off_plan,For Sale: Finished Apartment+ ACs in Village West,"5,145,000.00",sell,EGP,"Village West, Sheikh Zayed Compounds, Sheikh Z...",Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Village West,30.05,31.02,2,2,123.00,sqm,PARTLY,premium,True,False,False,False,False,False,2026-03-04T11:24:23Z,10,False,NaN,rb304,NaN,For Sale: Finished Apartment with ACs in Villa...,Balcony | Built in Wardrobes | Central A/C | C...,cash,"67,166.00",Rana Bahaa ElDeen,ranoushamer901@gmail.com,False,NaN,492.00,Abrag Real Estate,snawara71@gmail.com,"201,001,188,088.00","201,007,169,666.00","20,221,257,340.00",ranoushamer901@gmail.com,2026-03-04T14:20:33.281007
2,Q6GEB8T6PZTJGNNPWA5PX3JCWR,"56,253,883.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,UnderMarket Price for Apt. 250 RTM PrimeLocation,"10,800,000.00",sell,EGP,"Palm Hills New Cairo, 5th Settlement Compounds...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.01,31.58,4,4,250.00,sqm,NaN,premium,True,False,False,False,False,False,2026-03-04T14:03:51Z,13,False,NaN,250pncash,NaN,Palm Hills New Cairo Apartment BUA: 250sqm 4 B...,Balcony | Built in Wardrobes | Central A/C | C...,cash,"47,158.00",Ashraf Shaaban,ashrafsobhy99@hotmail.com,False,English | Arabic,"5,279.00",Premises,mahmouddessam@hotmail.com,"201,005,133,389.00","201,090,963,241.00","20,221,257,340.00",ashrafsobhy99@hotmail.com,2026-03-04T14:20:33.281007
3,PPH0852SAB266X6GSVATJP4F0M,"56,250,852.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,lowest price 2bds fullyfurnished @ lake view,"10,500,000.00",sell,EGP,"Lake View Residence, 5th Settlement Compounds,...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.03,31.54,2,2,136.00,sqm,YES,premium,True,False,False,False,False,False,2026-03-04T12:38:11Z,11,False,NaN,PPH0852SAB266X6GSVATJP4F0M,NaN,Lake View Residence 136 sqm Fully Finished Ren...,Balcony | Built in Wardrobes | Central A/C | C...,cash,"63,401.00",ebrahim hossam,ebrahim.hossam@spade-consultancy.com,False,NaN,"5,758.00",Spade consultancy,mohmedg.sedik@gmail.com,"1,001,436,511.00","201,070,115,211.00","20,221,257,340.00",ebrahim.hossam@spade-consultancy.com,2026-03-04T14:20:33.281007
4,QCSA4TNDEBBV7BNY8ANST3TB50,"55,995,764.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/villa...,Villa,Residential for Sale,completed,Exclusive Type M with Lowest Price RTM in PNC,"19,500,000.00",sell,EGP,"Palm Hills New Cairo, 5th Settlement Compounds...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.01,31.58,4,4,255.00,sqm,NaN,premium,True,False,False,False,False,False,2026-03-03T09:45:41Z,17,False,NaN,VillTyM,NaN,Palm Hills New Cairo Type M BUA: 255sqm LAND: ...,Balcony | Built in Wardrobes | Central A/C | C...,cash,"47,158.00",Ashraf Shaaban,ashrafsobhy99@hotmail.com,False,English | Arabic,"5,279.00",Premises,mahmouddessam@hotmail.com,"201,005,133,389.00","201,090,963,241.00","20,221,257,340.00",ashrafsobhy99@hotmail.com,2026-03-04T14:20:33.281007
6,8QH1VD951AYY4QFV05F0VND6BM,"56,253,782.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,For Sale: 209m Apartment with Garden in Address,"11,750,000.00",sell,EGP,"The Address, 12th District, Sheikh Zayed City,...",Giza,Sheikh Zayed City,12th District,The Address,30.04,30.99,4,2,209.00,sqm,NO,premium,True,False,False,False,False,False,2026-03-04T13:57:39Z,24,False,NaN,8QH1VD951AYY4QFV05F0VND6BM,NaN,"For Sale: 209m Apartment with Garden, Finished...",Balcony | Central A/C | Built in Wardrobes | S...,cash,"66,482.00",Reham Hossam,rehamhos123@gmail.com,False,NaN,492.00,Abrag Real Estate,snawara71@gmail.com,"201,001,188,088.00","201,030,629,875.00","20,221,257,340.00",rehamhos123@gmail.com,2026-03-04T14:20:33.281007
7,MSKBV5SGQKC27G4GAFJFTXEVP8,"8,661,745.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/penth...,Penthouse,Residential for Sale,completed,Fully furnished Penthouse for sale direct on lake,"7,200,000.00",sell,EGP,"Amwaj, Sidi Abdel Rahman, North Coast",North Coast,Sidi Abdel Rahman,Amwaj,NaN,31.00,28.68,2,1,85.00,sqm,YES,premium,True,False,False,False,False,False,2026-02-05T17:32:08Z,10,False,NaN,MSKBV5SGQKC27G4GAFJFTXEVP8,NaN,Amwaj North Coast Penthouse with Roof for sale...,Balcony | Built in Wardrobes | Central A/C | C...,cash,"21,629.00",Mona Ashraf,mona.imageinv@gmail.com,False,English | Arabic,"1,480.00",Image Investments,lotfyahmed050@gmail.com,"201,099,227,303.00","201,222,150,872.00","20,221,257,340.00",mona.imageinv@gmail.com,2026-03-04T14:20:33.281007
8,32X4G4P799SP6QWFSPRZPP1K6M,"53,990,550.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,Ready-to-move apt at the lowest price aeon Tower,"30,000,000.00",sell,EGP,"Aeon, 6 October Compounds, 6 October City, Giza",Giza,6 October City,6 October Compounds,Aeon,30.01,30.97,3,3,285.00,sqm,NO,premium,True,False,False,False,False,False,2026-02-23T19:55:15Z,21,False,NaN,aeon towers-2,NaN,Eon Towers - marakez -------------------------...,Balcony | Built in Wardrobes | Covered Parking...,cash,"70,927.00",sahar negm,saharnegm756@gmail.com,False,English | Arabic,"5,456.00",Sequoia,safwatnasr90@gmail.com,"201,222,222,606.00","201,030,542,923.00","20,221,257,340.00",saharnegm756@gmail.com,2026-03-04T14:20:33.281007
9,YW40RV7JXP0GVN8BV26V64KS88,"8,540,695.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,Swan Lake Gouna’s Last Unit — Flexible Install...,"23,250,000.00",sell,EGP,"Swan Lake Gouna, El Gouna, Hurghada, Red Sea",Red Sea,Hurghada,El Gouna,Swan Lake Gouna,27.41,33.66,3,2,144.00,sqm,YES,premium,True,False,False,False,False,False,2026-01-14T12:16:11Z,10,False,NaN,YW40RV7JXP0GVN8BV26V64KS88,NaN,HAP Resale EXP. is Hassan Allam Properties Res...,Balcony | Built in Wardrobes | Kitchen Applian...,cash,"59,718.00",Sarah Fahmy,sfahmy@hap.com.eg,False,NaN,"6,115.00",HAP RESALE Exp,sguemeih@hap.com.eg,"1,014,277,708.00","201,222,764,998.00","20,221,257,340.00",sfahmy@hap.com.eg,2026-03-04T14:20:33.281007
10,9SPE6HSBTAX5A0SZ8CARV1JTMM,"56,003,501.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/villa...,Villa,Residential for Sale,completed,lowest type B villa ready to move at Palm hills,"47,000,000.00",sell,EGP,"Palm Hills New Cairo, 5th Settlement Compounds...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.01,31.58,6,7+,963.00,sqm,NaN,premium,True,False,False,False,False,False,2026-03-03T13:11:43Z,13,False,NaN,9SPE6HSBTAX5A0SZ8CARV1JTMM,NaN,Palm Hills New Cairo Type B BUA:607 LAND: 963 ...,Balcony | Central A/C | Built in Wardrobes | C...,cash,"67,498.00",Dalia Hazem,daliahazem999@gmail.com,False,NaN,"5,279.00",Premises,mahmouddessam@hotmail.com,"201,005,133,389.00","201,272,333,175.00","20,221,257,340.00",daliahazem999@gmail.com,2026-03-04T14:20:33.281007
11,RS5MK1WXFB5NNY5ACD23JYNZEW,"55,746,259.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/twin-...,Twin House,Residential for Sale,completed,Twinhouse in Levana with Smart System,"37,000,000.00",sell,EGP,"Uptown Cairo Road, Al Abageyah, El Khalifa, Cairo",Cairo,El Khalifa,Al Abageyah,Uptown Cairo Road,30.02,31.29,5,4,320.00,sqm,NO,premium,True,False,False,False,False,False,2026-03-02T04:25:37Z,10,False,NaN,RS5MK1WXFB5NNY5ACD23JYNZEW,NaN,Uptown cairo - levana Twinhouse for sale ready...,Balcony | Study | Security,cash,"63,799.00",Aya Adel,aya.adel@spade-consultancy.com,False,NaN,"5,758.00",Spade consultancy,mohmedg.sedik@gmail.com,"1,001,436,511.00","201,107,647,164.00","20,221,257,340.00",aya.adel@spade-consultancy.com,2026-03-04T14:20:33.281007
12,01KBW7DX1FS1EKF60HD3FCAW92,"8,393,263.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/twin-...,Twin House,Residential for Sale,completed,Hassle free Purchase! twin directly through HAP,"27,750,000.00",sell,EGP,"Swan Lake North Coast, Qesm Ad Dabaah, North C...",North Coast,Qesm Ad Dabaah,Swan Lake North Coast,NaN,31.07,28.06,4,4,265.00,sqm,NO,premium,True,False,False,False,False,False,2025-12-10T10:56:05Z,10,False,NaN,01KBW7DX1FS1EKF60HD3FCAW92,NaN,HAP Resale EXP. is Hassan Allam Properties Res...,Maids Room | Security | Built in Wardrobes,cash,"59,716.00",Youssef Khafagy,ykafagy@hap.com.eg,False,NaN,"6,115.00",HAP RESALE Exp,sguemeih@hap.com.eg,"1,014,277,708.00","201,062,312,362.00","20,221,257,340.00",ykafagy@hap.com.eg,2026-03-04T14:20:33.281007
13,01KBA9XB799436ATVN37344BDJ,"8,364,341.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/townh...,Townhouse,Residential for Sale,completed,Opportunity Lowest price Town house middle,"21,000,000.00",sell,EGP,"Swan Lake Residence, 5th Settlement Compounds,...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.07,31.47,3,3,226.00,sqm,NaN,premium,True,False,False,False,False,False,2025-12-04T12:23:22Z,6,False,NaN,01KBA9XB799436ATVN37344BDJ,NaN,HAP Resale EXP. is Hassan Allam Properties Res...,Balcony | Maids Room | Private Garden | Security,cash,"59,716.00",Youssef Khafagy,ykafagy@hap.com.eg,False,NaN,"6,115.00",HAP RESALE Exp,sguemeih@hap.com.eg,"1,014,277,708.00","201,062,312,362.00","20,221,257,340.00",ykafagy@hap.com.eg,2026-03-04T14:20:33.281007
14,HJ7S6JN66FE31T7XSD0BJ6VY48,"56,253,326.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/villa...,Villa,Residential for Sale,completed,Under Market Price Villa 415m 5 Bed Ready To Move,"31,500,000.00",sell,EGP,"Palm Hills Katameya Extension, 5th Settlement ...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.04,31.54,5,5,415.00,sqm,NaN,premium,True,False,False,False,False,False,2026-03-04T13:41:34Z,10,False,NaN,PK2z1,NaN,Palm Hills Katameya Extension Standalone Villa...,Balcony | Built in Wardrobes | Central A/C | C...,cash,"47,159.00",Mouris Samir,mouris21mouris@gmail.com,False,English | Arabic,"5,279.00",Premises,mahmouddessam@hotmail.com,"201,005,133,389.00","201,277,736,450.00","20,221,257,340.00",mouris21mouris@gmail.com,2026-03-04T14:20:33.281007
15,4EP7DKBWG1F67A4XZ0XT81ZHHM,"56,253,335.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/villa...,Villa,Residential for Sale,completed,Standalone Villa for Sale in Swan Lake Residence,"85,000,000.00",sell,EGP,"Swan Lake Residence, 5th Settlement Compounds,...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.07,31.47,5,6,652.00,sqm,NaN,premium,True,False,False,False,False,False,2026-03-04T13:42:17Z,10,False,NaN,AA-MH-0077,NaN,Standalone Villa for Sale in Swan Lake Residen...,Balcony | Maids Room | Security | View of Land...,cash,"69,876.00",Hala Abu ElNaga,Hala.Abulnaga@beltoneholding.com,False,NaN,"6,313.00",Beltone,kee.contactus@beltoneholding.com,"1,033,329,264.00","201,033,329,264.00","20,221,257,340.00",Hala.Abulnaga@beltoneholding.com,2026-03-04T14:20:33.281007
16,7CG8G90ACX3FF8TAXXCM1GDRTG,"56,246,674.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed_primary,"155 sqm fully finished AP with AC near delivery,","2,000,000.00",sell,EGP,"Park Side Residence, Zed Towers, Sheikh Zayed ...",Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Zed Towers,30.05,31.00,3,3,155.00,sqm,NO,premium,True,False,False,False,False,False,2026-03-04T10:55:53Z,13,False,NaN,7CG8G90ACX3FF8TAXXCM1GDRTG,NaN,A prime opportunity for living and investment ...,Private Garden | Covered Parking | Balcony | B...,cash | installments,"60,778.00",Sohaila Alaa,sohilaalaa9921@gmail.com,False,NaN,"5,645.00",property hills Elite,ng.noragamal@gmail.com,"1,018,706,385.00","201,018,976,709.00","201,018,976,709.00",sohilaalaa9921@gmail.com,2026-03-04T14:20:33.281007
17,XGK5TR3SB9YCFHCZEV95QBJSPG,"55,761,843.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,Apartment for sale with Landscape view RTM,"5,700,000.00",sell,EGP,"Mountain View iCity, 5th Settlement Compounds,...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.07,31.60,3,3,155.00,sqm,NaN,premium,True,False,False,False,False,False,2026-03-02T19:36:00Z,15,False,NaN,mvicityclubpark1,NaN,With the Lowest Price Apartment with lowest pr...,Covered Parking | Shared Pool | Study | Securi...,cash,"53,731.00",Dalia Alaa,Daliaalaaeldin99@gmail.com,False,NaN,"3,928.00",Assets Real Estate Investments,ahmed.ragab.mamoun@gmail.com,"201,150,966,263.00","201,200,100,885.00","201,200,100,885.00",Daliaalaaeldin99@gmail.com,2026-03-04T14:20:33.281007
18,X5YG17SFDMQ6BD98V37SVGGQ7C,"56,253,077.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/duple...,Duplex,Residential for Sale,off_plan,I Villa Roof For Sale In Mountain View I city New,"9,390,000.00",sell,EGP,"Mountain View iCity, 5th Settlement Compounds,...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.07,31.60,3,3,280.00,sqm,NaN,premium,True,False,False,False,False,False,2026-03-04T13:33:51Z,27,False,NaN,Karima-88,NaN,Mountain View iCity – New Cairo Developer: Mou...,Balcony | Built in Wardrobes | Maids Room | St...,cash,"73,437.00",Karima Hamdy,Karimahamdy24@gmail.com,False,NaN,"6,447.00",the address Investment Mostafa Refaai,maghfera.ashraf@addressinv.com,"1,090,353,564.00","201,090,731,021.00","20,221,257,340.00",Karimahamdy24@gmail.com,2026-03-04T14:20:33.281007
19,01KB054PAMGTN6QBKY72PT97PQ,"8,325,347.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/villa...,Villa,Residential for Sale,completed_primary,Own a luxurious 5-bedroom villa with 5% downpa...,"16,000,000.00",sell,EGP,"Palm Hills New Cairo, 5th Settlement Compounds...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.01,31.58,5,5,300.00,sqm,PARTLY,premium,True,False,False,False,False,False,2025-11-26T14:21:58Z,10,False,NaN,phncvilla-01KB054PAM,NaN,Villa for sale with an open view in Palm Hills...,Balcony | Built in Wardrobes | Central A/C | C...,installments,"16,448.00",Mohamed Mostafa,m.mostafa@egyptbestproperties.com,False,NaN,85.00,Egypt Best Properties,info@egyptbestproperties.com,"201,224,946,565.00","201,200,024,116.00","20,221,257,340.00",m.mostafa@egyptbestproperties.com,2026-03-04T14:20:33.281007
20,3YEKJHFQ500G4ZE1MA7EH75T88,"56,252,057.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/villa...,Villa,Residential for Sale,completed,Luxury Standalone Villa For Sale Limited Offer,"63,000,000.00",sell,EGP,"Silver Sands, Qesm Marsa Matrouh, North Coast",North Coast,Qesm Marsa Matrouh,Silver Sands,NaN,31.27,27.38,6,6,304.00,sqm,PARTLY,premium,True,False,False,False,False,False,2026-03-04T13:08:58Z,10,False,NaN,3YEKJHFQ500G4ZE1MA7EH75T88....A.W,NaN,Project Name : Silversands Developer Name : Or...,Balcony | Built in Wardrobes | Central A/C | C...,cash,"18,382.00",Omneya Samy,omneya@egyptbestproperties.com,False,NaN,85.00,Egypt Best Properties,info@egyptbestproperties.com,"201,224,946,565.00","201,200,060,015.00","20,221,257,340.00",omneya@egyptbestproperties.com,2026-03-04T14:20:33.281007
21,W4K35V6Q5YXAKK5R5QB95P9R6M,"56,251,887.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,off_plan_primary,"138 sqm apt in Beta October, 9-year plan, 5% DP","6,250,600.00",sell,EGP,"BETA Residence, Hadayek October, 6 October Cit...",Giza,6 October City,Hadayek October,BETA Residence,29.91,31.08,2,2,138.00,sqm,NaN,premium,True,False,False,False,False,False,2026-03-04T13:04:55Z,10,False,NaN,ZF565,NaN,Own your apartment now in Beta Compound with o...,Balcony | View of Landmark | Shared Gym | Secu...,cash | installments,"67,826.00",Zeyad Fouda,zeyadfouda50@gmail.com,False,NaN,"4,774.00",Vida Solutions,vidasolution2023@gmail.com,"201,033,919,888.00","201,096,302,355.00","20,221,257,340.00",zeyadfouda50@gmail.com,2026-03-04T14:20:33.282527
22,XZPRBE0SCE072BKC0X1809W310,"56,240,498.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,"Apartment for sale in Jannah 2, 150 square met...","3,500,000.00",sell,EGP,"Janna 2, Sheikh Zayed Compounds, Sheikh Zayed ...",Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Janna 2,30.04,30.99,3,3,150.00,sqm,NO,premium,True,False,False,False,False,False,2026-03-04T00:18:34Z,10,False,NaN,XZPRBE0SCE072BKC0X1809W310,NaN,Ground floor apartment for sale in Jannah 2 Co...,Balcony | Built in Wardrobes | Covered Parking...,cash,"35,669.00",Hoda,hodaelbouhypf@gmail.com,False,NaN,362.00,Master Key,msawy3333@gmail.com,"201,067,689,033.00","201,111,316,369.00","20,221,257,340.00",hodaelbouhypf@gmail.com,2026-03-04T14:20:33.282527
23,PY8CCC443Z3QCY91J4BNMG1B3G,"56,246,468.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,Lowest Price Studio Sale W Kitchen-Ac's Zed West,"5,330,000.00",sell,EGP,"Park Side Residence, Zed Towers, Sheikh Zayed ...",Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Zed Towers,30.05,31.00,studio,1,56.00,sqm,PARTLY,premium,True,False,False,False,False,False,2026-03-04T10:49:51Z,8,False,NaN,ahmedsayed77,NaN,A fully finished apartment for sale with immed...,Balcony | Built in Wardrobes | Central A/C | C...,cash,"71,970.00",Ahmed Sayed,ahmed.sayed@drivenegypt.com,False,NaN,"4,778.00",Driven Properties,info@drivenegypt.com,"201,026,669,361.00","201,026,690,945.00","20,221,257,340.00",ahmed.sayed@drivenegypt.com,2026-03-04T14:20:33.282527
24,SCQNQ7G0K6DBBT5243C2X77SPM,"56,252,738.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/townh...,Townhouse,Residential for Sale,completed,Resale Cheapest Corner Town House + Garden 110 m,"9,700,000.00",sell,EGP,"Mountain View, Ras Al Hekma, North Coast",North Coast,Ras Al Hekma,Mountain View,NaN,30.82,29.12,3,4,145.00,sqm,NaN,premium,True,False,False,False,False,False,2026-03-04T13:23:15Z,10,False,NaN,Y-MV12-12,NaN,-Details : • Built up area : 145 sqm • Garden ...,Built in Wardrobes | Central A/C | Balcony | C...,cash,"42,571.00",Hadeer Ahmed,info@oqood-eg.com,False,English | Arabic,"4,755.00",Oqood Investments,ahmed.emaduldeen@gmail.com,"201,097,858,301.00","201,004,022,902.00","201,004,022,902.00",info@oqood-eg.com,2026-03-04T14:20:33.282719