In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("propertyfinder.csv")

C:\Users\dell\AppData\Local\Temp\ipykernel_15236\4033129182.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("propertyfinder.csv")

In [3]:
df

,listing_id,internal_id,category,listing_type,detail_url,property_type,offering_type,completion_status,title,price_egp,...,agent_is_super,agent_languages,broker_id,broker_name,broker_email,broker_phone,contact_phone,contact_whatsapp,contact_email,scraped_at
0,F7QB31CGWE509V2W7DF2GARB2C,56009081.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/duple...,Duplex,Residential for Sale,completed,Garden Villa - Lake View Boutique - Prime Loca...,24500000.0,...,False,NaN,5758.0,Spade consultancy,mohmedg.sedik@gmail.com,1.001437e+09,2.012018e+11,2.022126e+10,pierre.Osama@spade-consultancy.com,2026-03-04T14:20:33.281007
1,K1JC3D6N57ED52N3VX1QQKHHXG,56247925.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,off_plan,For Sale: Finished Apartment+ ACs in Village West,5145000.0,...,False,NaN,492.0,Abrag Real Estate,snawara71@gmail.com,2.010012e+11,2.010072e+11,2.022126e+10,ranoushamer901@gmail.com,2026-03-04T14:20:33.281007
2,Q6GEB8T6PZTJGNNPWA5PX3JCWR,56253883.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,UnderMarket Price for Apt. 250 RTM PrimeLocation,10800000.0,...,False,English | Arabic,5279.0,Premises,mahmouddessam@hotmail.com,2.010051e+11,2.010910e+11,2.022126e+10,ashrafsobhy99@hotmail.com,2026-03-04T14:20:33.281007
3,PPH0852SAB266X6GSVATJP4F0M,56250852.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,lowest price 2bds fullyfurnished @ lake view,10500000.0,...,False,NaN,5758.0,Spade consultancy,mohmedg.sedik@gmail.com,1.001437e+09,2.010701e+11,2.022126e+10,ebrahim.hossam@spade-consultancy.com,2026-03-04T14:20:33.281007
4,QCSA4TNDEBBV7BNY8ANST3TB50,55995764.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/villa...,Villa,Residential for Sale,completed,Exclusive Type M with Lowest Price RTM in PNC,19500000.0,...,False,English | Arabic,5279.0,Premises,mahmouddessam@hotmail.com,2.010051e+11,2.010910e+11,2.022126e+10,ashrafsobhy99@hotmail.com,2026-03-04T14:20:33.281007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39708,YQT77A2J44CPMV7H28J9V30ADR,8667639.0,rent,property,https://www.propertyfinder.eg/en/plp/rent/apar...,Apartment,Residential for Rent,NaN,"Furnished apartment for rent in Al Rehab, 250M",55000.0,...,False,NaN,4456.0,Escan Group,aahmdymagdy201070@gmail.com,2.011233e+11,2.011040e+11,2.022126e+10,atiasaad188@gmail.com,2026-03-05T00:43:04.172513
39709,8385GKAA00BXE8FYPWNQ29VF3M,8667632.0,rent,property,https://www.propertyfinder.eg/en/plp/rent/apar...,Apartment,Residential for Rent,NaN,FULLY FURNISHED apartment for RENT 3 Bedroom,45000.0,...,False,NaN,430.0,RE/MAX Al Mohager,m.degheady@remax.com.eg,2.010308e+11,2.010947e+11,2.022126e+10,yuliya.hassan@remax.com.eg,2026-03-05T00:43:04.172513
39710,R9PTSC3V5RZ77ZT9X69TBE1PEC,8667625.0,rent,property,https://www.propertyfinder.eg/en/plp/rent/town...,Townhouse,Residential for Rent,NaN,Furnished villa for rent in Town 5 rooms near New,120000.0,...,False,NaN,4679.0,Abrag 2,NaN,NaN,2.011146e+11,2.022126e+10,Mahmoudalabasy94@gmail.com,2026-03-05T00:43:04.172513
39711,9Q295E8B6ET3V30Z31925BR6ZG,8667615.0,rent,property,https://www.propertyfinder.eg/en/plp/rent/apar...,Apartment,Residential for Rent,NaN,For Rent – Premium 196m² Fully Finished Apartment,50000.0,...,False,NaN,430.0,RE/MAX Al Mohager,m.degheady@remax.com.eg,2.010308e+11,2.010707e+11,2.022126e+10,yalashwat2000@gmail.com,2026-03-05T00:43:04.172513
39712,HYEPN5XPWQT7K05K4ST7EDWW5R,8667602.0,rent,property,https://www.propertyfinder.eg/en/plp/rent/apar...,Apartment,Residential for Rent,NaN,If you're looking hotel units contact us now,75000.0,...,False,English | Arabic,5307.0,Smart Home,ahmedbompo9@gmail.com,2.010120e+11,2.010408e+11,2.022126e+10,sh2927333@gmail.com,2026-03-05T00:43:04.172513

In [4]:
df.isnull().sum()

listing_id                 1
internal_id                1
category                   0
listing_type               0
detail_url                 1
property_type              1
offering_type              1
completion_status      19950
title                      1
price_egp                  1
price_period               1
price_currency             0
location_full              1
city                       1
town                       1
district                 347
subdistrict             6759
lat                        1
lon                        1
bedrooms                  35
bathrooms                 30
area_value                 1
area_unit                  0
furnished               8385
listing_level              1
is_premium                 0
is_verified                0
is_featured                0
is_new_construction        0
is_direct_from_dev         0
is_exclusive               0
listed_date                1
images_count               0
has_view_360               0
video_url              39511
reference                  1
rera                   39713
description                1
amenities                 33
payment_method         19774
agent_id                   1
agent_name                 8
agent_email                1
agent_is_super             0
agent_languages        30541
broker_id                  1
broker_name                1
broker_email             203
broker_phone             203
contact_phone              1
contact_whatsapp           1
contact_email              1
scraped_at                 0
dtype: int64

In [6]:
df_sorted = df.sort_values(by='area_value')
df_sorted['area_value']
pd.set_option('display.max_rows',10)
pd.set_option('display.min_rows',10)
pd.set_option('display.max_columns',50)

In [9]:
df.nunique()

listing_id          39712
internal_id         39712
category                2
listing_type            2
detail_url          39712
                    ...
broker_phone          769
contact_phone        2483
contact_whatsapp      422
contact_email        2732
scraped_at           4736
Length: 53, dtype: int64

In [11]:
df['property_type'].unique()

array(['Duplex', 'Apartment', 'Villa', nan, 'Penthouse', 'Twin House',
       'Townhouse', 'Chalet', 'iVilla', 'Hotel Apartment',
       'Whole Building', 'Half Floor', 'Land', 'Bulk Sale Unit', 'Cabin',
       'Roof', 'Palace', 'Full Floor', 'Bulk Rent Unit', 'Bungalow'],
      dtype=object)

In [12]:
columns_to_keep = [
    'category',
    'property_type',
    'offering_type',
    'completion_status',
    'price_egp',
    'price_period',
    'city',
    'town',
    'district',
    'lat',
    'lon',
    'bedrooms',
    'bathrooms',
    'area_value',
    'furnished',
    'listing_level',
    'is_premium',
    'is_featured',
    'listed_date',
    'payment_method',
    'agent_id',
    'broker_id',
]
df = df[columns_to_keep]
df

,category,property_type,offering_type,completion_status,price_egp,price_period,city,town,district,lat,lon,bedrooms,bathrooms,area_value,furnished,listing_level,is_premium,is_featured,listed_date,payment_method,agent_id,broker_id
0,buy,Duplex,Residential for Sale,completed,24500000.0,sell,Cairo,New Cairo City,The 5th Settlement,30.040602,31.525942,3,6,445.0,NaN,premium,True,False,2026-03-03T19:15:06Z,cash,58866.0,5758.0
1,buy,Apartment,Residential for Sale,off_plan,5145000.0,sell,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,30.048094,31.020054,2,2,123.0,PARTLY,premium,True,False,2026-03-04T11:24:23Z,cash,67166.0,492.0
2,buy,Apartment,Residential for Sale,completed,10800000.0,sell,Cairo,New Cairo City,The 5th Settlement,30.012272,31.579515,4,4,250.0,NaN,premium,True,False,2026-03-04T14:03:51Z,cash,47158.0,5279.0
3,buy,Apartment,Residential for Sale,completed,10500000.0,sell,Cairo,New Cairo City,The 5th Settlement,30.026146,31.536974,2,2,136.0,YES,premium,True,False,2026-03-04T12:38:11Z,cash,63401.0,5758.0
4,buy,Villa,Residential for Sale,completed,19500000.0,sell,Cairo,New Cairo City,The 5th Settlement,30.012272,31.579515,4,4,255.0,NaN,premium,True,False,2026-03-03T09:45:41Z,cash,47158.0,5279.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39708,rent,Apartment,Residential for Rent,NaN,55000.0,monthly,Cairo,New Cairo City,Al Rehab,30.061470,31.511395,3,3,250.0,YES,standard,False,False,2026-02-07T16:33:32Z,NaN,68162.0,4456.0
39709,rent,Apartment,Residential for Rent,NaN,45000.0,monthly,Giza,6 October City,Cairo Alexandria Desert Road,30.011623,31.087412,3,3,180.0,YES,standard,False,False,2026-02-07T16:32:23Z,NaN,23636.0,430.0
39710,rent,Townhouse,Residential for Rent,NaN,120000.0,monthly,Giza,6 October City,Cairo Alexandria Desert Road,30.007010,31.042629,5,5,320.0,YES,standard,False,False,2026-02-07T16:31:32Z,NaN,16061.0,4679.0
39711,rent,Apartment,Residential for Rent,NaN,50000.0,monthly,Giza,6 October City,Cairo Alexandria Desert Road,30.006905,31.059334,2,2,196.0,NO,standard,False,False,2026-02-07T16:29:24Z,NaN,60109.0,430.0
39712,rent,Apartment,Residential for Rent,NaN,75000.0,monthly,Cairo,New Cairo City,The 5th Settlement,30.022596,31.545815,2,2,144.0,YES,standard,False,False,2026-02-07T16:26:50Z,NaN,56917.0,5307.0

In [13]:
df_buy=df[df['category']=='buy']
df_buy

,category,property_type,offering_type,completion_status,price_egp,price_period,city,town,district,lat,lon,bedrooms,bathrooms,area_value,furnished,listing_level,is_premium,is_featured,listed_date,payment_method,agent_id,broker_id
0,buy,Duplex,Residential for Sale,completed,24500000.0,sell,Cairo,New Cairo City,The 5th Settlement,30.040602,31.525942,3,6,445.0,NaN,premium,True,False,2026-03-03T19:15:06Z,cash,58866.0,5758.0
1,buy,Apartment,Residential for Sale,off_plan,5145000.0,sell,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,30.048094,31.020054,2,2,123.0,PARTLY,premium,True,False,2026-03-04T11:24:23Z,cash,67166.0,492.0
2,buy,Apartment,Residential for Sale,completed,10800000.0,sell,Cairo,New Cairo City,The 5th Settlement,30.012272,31.579515,4,4,250.0,NaN,premium,True,False,2026-03-04T14:03:51Z,cash,47158.0,5279.0
3,buy,Apartment,Residential for Sale,completed,10500000.0,sell,Cairo,New Cairo City,The 5th Settlement,30.026146,31.536974,2,2,136.0,YES,premium,True,False,2026-03-04T12:38:11Z,cash,63401.0,5758.0
4,buy,Villa,Residential for Sale,completed,19500000.0,sell,Cairo,New Cairo City,The 5th Settlement,30.012272,31.579515,4,4,255.0,NaN,premium,True,False,2026-03-03T09:45:41Z,cash,47158.0,5279.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19798,buy,Apartment,Residential for Sale,completed,7000000.0,sell,Cairo,Madinaty,Privado,30.091936,31.665174,3,2,125.0,NO,standard,False,False,2026-02-27T12:52:18Z,cash,69259.0,6229.0
19799,buy,Chalet,Residential for Sale,off_plan_primary,1666000.0,sell,North Coast,Al Alamein,Golf Porto Marina,30.841496,28.923971,2,1,60.0,NaN,standard,False,False,2026-02-27T12:52:11Z,cash,70412.0,4650.0
19800,buy,Twin House,Residential for Sale,completed_primary,7000000.0,sell,Giza,6 October City,6 October Compounds,29.957909,30.915758,3,4,50.0,NaN,standard,False,False,2026-02-27T12:51:37Z,cash | installments,67568.0,6126.0
19801,buy,Villa,Residential for Sale,completed_primary,7200000.0,sell,Giza,6 October City,6 October Compounds,29.957909,30.915758,3,4,20.0,NaN,standard,False,False,2026-02-27T12:51:02Z,cash | installments,67568.0,6126.0
19802,buy,Apartment,Residential for Sale,completed,12700000.0,sell,Cairo,New Cairo City,The 5th Settlement,30.011169,31.516115,3,3,156.0,NO,standard,False,False,2026-02-27T12:50:53Z,cash,48304.0,5373.0

In [14]:
df_rent=df[df['category']=='rent']
df_rent

,category,property_type,offering_type,completion_status,price_egp,price_period,city,town,district,lat,lon,bedrooms,bathrooms,area_value,furnished,listing_level,is_premium,is_featured,listed_date,payment_method,agent_id,broker_id
19803,rent,Apartment,Residential for Rent,NaN,35000.0,monthly,Cairo,New Cairo City,The 5th Settlement,30.025003,31.594761,2,2,128.0,PARTLY,premium,True,False,2026-03-04T21:13:08Z,NaN,55901.0,5389.0
19804,rent,Apartment,Residential for Rent,NaN,50000.0,monthly,Cairo,New Cairo City,El Banafseg,30.046291,31.473789,3,3,300.0,NO,premium,True,False,2026-03-04T12:47:53Z,NaN,66449.0,2520.0
19805,rent,Apartment,Residential for Rent,NaN,45000.0,monthly,Cairo,New Cairo City,El Yasmeen,30.048929,31.447016,3,3,210.0,YES,premium,True,False,2026-03-04T11:12:17Z,NaN,66449.0,2520.0
19806,rent,Apartment,Residential for Rent,NaN,25000.0,monthly,Cairo,New Cairo City,Abou El Houl,29.982248,31.468801,2,2,150.0,NO,premium,True,False,2026-03-04T10:58:28Z,NaN,50635.0,2520.0
19807,rent,Apartment,Residential for Rent,NaN,40000.0,monthly,Cairo,New Cairo City,The 1st Settlement,30.052275,31.444633,2,2,130.0,YES,premium,True,False,2026-03-04T09:19:33Z,NaN,44158.0,2520.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39708,rent,Apartment,Residential for Rent,NaN,55000.0,monthly,Cairo,New Cairo City,Al Rehab,30.061470,31.511395,3,3,250.0,YES,standard,False,False,2026-02-07T16:33:32Z,NaN,68162.0,4456.0
39709,rent,Apartment,Residential for Rent,NaN,45000.0,monthly,Giza,6 October City,Cairo Alexandria Desert Road,30.011623,31.087412,3,3,180.0,YES,standard,False,False,2026-02-07T16:32:23Z,NaN,23636.0,430.0
39710,rent,Townhouse,Residential for Rent,NaN,120000.0,monthly,Giza,6 October City,Cairo Alexandria Desert Road,30.007010,31.042629,5,5,320.0,YES,standard,False,False,2026-02-07T16:31:32Z,NaN,16061.0,4679.0
39711,rent,Apartment,Residential for Rent,NaN,50000.0,monthly,Giza,6 October City,Cairo Alexandria Desert Road,30.006905,31.059334,2,2,196.0,NO,standard,False,False,2026-02-07T16:29:24Z,NaN,60109.0,430.0
39712,rent,Apartment,Residential for Rent,NaN,75000.0,monthly,Cairo,New Cairo City,The 5th Settlement,30.022596,31.545815,2,2,144.0,YES,standard,False,False,2026-02-07T16:26:50Z,NaN,56917.0,5307.0

In [15]:
df_rent.drop(columns=['price_period'],inplace=True,errors='ignor')
df_buy.drop(columns=['price_period'], inplace=True, errors='ignore')

C:\Users\dell\AppData\Local\Temp\ipykernel_15236\1664211862.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rent.drop(columns=['price_period'],inplace=True,errors='ignor')
C:\Users\dell\AppData\Local\Temp\ipykernel_15236\1664211862.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_buy.drop(columns=['price_period'], inplace=True, errors='ignore')

In [16]:
df_rent.head(10)

,category,property_type,offering_type,completion_status,price_egp,city,town,district,lat,lon,bedrooms,bathrooms,area_value,furnished,listing_level,is_premium,is_featured,listed_date,payment_method,agent_id,broker_id
19803,rent,Apartment,Residential for Rent,NaN,35000.0,Cairo,New Cairo City,The 5th Settlement,30.025003,31.594761,2,2,128.0,PARTLY,premium,True,False,2026-03-04T21:13:08Z,NaN,55901.0,5389.0
19804,rent,Apartment,Residential for Rent,NaN,50000.0,Cairo,New Cairo City,El Banafseg,30.046291,31.473789,3,3,300.0,NO,premium,True,False,2026-03-04T12:47:53Z,NaN,66449.0,2520.0
19805,rent,Apartment,Residential for Rent,NaN,45000.0,Cairo,New Cairo City,El Yasmeen,30.048929,31.447016,3,3,210.0,YES,premium,True,False,2026-03-04T11:12:17Z,NaN,66449.0,2520.0
19806,rent,Apartment,Residential for Rent,NaN,25000.0,Cairo,New Cairo City,Abou El Houl,29.982248,31.468801,2,2,150.0,NO,premium,True,False,2026-03-04T10:58:28Z,NaN,50635.0,2520.0
19807,rent,Apartment,Residential for Rent,NaN,40000.0,Cairo,New Cairo City,The 1st Settlement,30.052275,31.444633,2,2,130.0,YES,premium,True,False,2026-03-04T09:19:33Z,NaN,44158.0,2520.0
19808,rent,Apartment,Residential for Rent,NaN,22000.0,Cairo,New Cairo City,The 5th Settlement,30.010021,31.444107,3,2,220.0,NO,premium,True,False,2026-03-04T10:27:24Z,NaN,44158.0,2520.0
19809,rent,Apartment,Residential for Rent,NaN,50000.0,Cairo,New Cairo City,The 5th Settlement,29.955320,31.449591,3,3,180.0,NO,premium,True,False,2026-03-04T20:32:58Z,NaN,35041.0,3944.0
19810,rent,Apartment,Residential for Rent,NaN,85000.0,Cairo,New Cairo City,The 5th Settlement,30.022596,31.545815,2,2,160.0,YES,premium,True,False,2026-03-04T19:44:59Z,NaN,47534.0,5307.0
19811,rent,Apartment,Residential for Rent,NaN,23000.0,Cairo,New Cairo City,El Lotus,30.034792,31.520737,3,2,175.0,NO,premium,True,False,2026-03-04T19:39:55Z,NaN,72093.0,6406.0
19812,rent,Apartment,Residential for Rent,NaN,95000.0,Cairo,New Cairo City,The 5th Settlement,30.022596,31.545815,3,3,191.0,YES,premium,True,False,2026-03-04T19:32:02Z,NaN,47534.0,5307.0

In [17]:
df_rent.drop(columns=['offering_type'],inplace=True,errors='ignore')

C:\Users\dell\AppData\Local\Temp\ipykernel_15236\4130103530.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rent.drop(columns=['offering_type'],inplace=True,errors='ignore')

In [18]:
df_rent.head()

,category,property_type,completion_status,price_egp,city,town,district,lat,lon,bedrooms,bathrooms,area_value,furnished,listing_level,is_premium,is_featured,listed_date,payment_method,agent_id,broker_id
19803,rent,Apartment,NaN,35000.0,Cairo,New Cairo City,The 5th Settlement,30.025003,31.594761,2,2,128.0,PARTLY,premium,True,False,2026-03-04T21:13:08Z,NaN,55901.0,5389.0
19804,rent,Apartment,NaN,50000.0,Cairo,New Cairo City,El Banafseg,30.046291,31.473789,3,3,300.0,NO,premium,True,False,2026-03-04T12:47:53Z,NaN,66449.0,2520.0
19805,rent,Apartment,NaN,45000.0,Cairo,New Cairo City,El Yasmeen,30.048929,31.447016,3,3,210.0,YES,premium,True,False,2026-03-04T11:12:17Z,NaN,66449.0,2520.0
19806,rent,Apartment,NaN,25000.0,Cairo,New Cairo City,Abou El Houl,29.982248,31.468801,2,2,150.0,NO,premium,True,False,2026-03-04T10:58:28Z,NaN,50635.0,2520.0
19807,rent,Apartment,NaN,40000.0,Cairo,New Cairo City,The 1st Settlement,30.052275,31.444633,2,2,130.0,YES,premium,True,False,2026-03-04T09:19:33Z,NaN,44158.0,2520.0

In [19]:
df_rent.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19910 entries, 19803 to 39712
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   category           19910 non-null  object
 1   property_type      19910 non-null  object
 2   completion_status  0 non-null      object
 3   price_egp          19910 non-null  float64
 4   city               19910 non-null  object
 5   town               19910 non-null  object
 6   district           19783 non-null  object
 7   lat                19910 non-null  float64
 8   lon                19910 non-null  float64
 9   bedrooms           19907 non-null  object
 10  bathrooms          19910 non-null  object
 11  area_value         19910 non-null  float64
 12  furnished          19765 non-null  object
 13  listing_level      19910 non-null  object
 14  is_premium         19910 non-null  bool
 15  is_featured        19910 non-null  bool
 16  listed_date        19910 non-null  object
 17  payment_method     137 non-null    object
 18  agent_id           19910 non-null  float64
 19  broker_id          19910 non-null  float64
dtypes: bool(2), float64(6), object(12)
memory usage: 2.9+ MB

In [ ]:
for dataframe in [df_rent, df_buy]:
  # Convert bedrooms and bathrooms to float / numeric
  dataframe['bedrooms'] = pd.to_numeric(dataframe['bedrooms'], errors='coerce')
  dataframe['bathrooms'] = pd.to_numeric(
      dataframe['bathrooms'], errors='coerce'
  )

 
  dataframe['listed_date'] = pd.to_datetime(dataframe['listed_date'])

  # Ensure agent_id and broker_id are treated as categorical/string IDs
  dataframe['agent_id'] = (
      dataframe['agent_id'].fillna(-1).astype(int).astype(str)
  )
  dataframe['broker_id'] = (
      dataframe['broker_id'].fillna(-1).astype(int).astype(str)
  )

In [21]:
df_buy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19803 entries, 0 to 19802
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   category           19803 non-null  object
 1   property_type      19802 non-null  object
 2   offering_type      19802 non-null  object
 3   completion_status  19763 non-null  object
 4   price_egp          19802 non-null  float64
 5   city               19802 non-null  object
 6   town               19802 non-null  object
 7   district           19583 non-null  object
 8   lat                19802 non-null  float64
 9   lon                19802 non-null  float64
 10  bedrooms           19194 non-null  float64
 11  bathrooms          19590 non-null  float64
 12  area_value         19802 non-null  float64
 13  furnished          11563 non-null  object
 14  listing_level      19802 non-null  object
 15  is_premium         19803 non-null  bool
 16  is_featured        19803 non-null  bool
 17  listed_date        19802 non-null  datetime64[ns, UTC]
 18  payment_method     19802 non-null  object
 19  agent_id           19803 non-null  object
 20  broker_id          19803 non-null  object
dtypes: bool(2), datetime64[ns, UTC](1), float64(6), object(12)
memory usage: 3.1+ MB

In [22]:
df_rent.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19910 entries, 19803 to 39712
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   category           19910 non-null  object
 1   property_type      19910 non-null  object
 2   completion_status  0 non-null      object
 3   price_egp          19910 non-null  float64
 4   city               19910 non-null  object
 5   town               19910 non-null  object
 6   district           19783 non-null  object
 7   lat                19910 non-null  float64
 8   lon                19910 non-null  float64
 9   bedrooms           19175 non-null  float64
 10  bathrooms          19825 non-null  float64
 11  area_value         19910 non-null  float64
 12  furnished          19765 non-null  object
 13  listing_level      19910 non-null  object
 14  is_premium         19910 non-null  bool
 15  is_featured        19910 non-null  bool
 16  listed_date        19910 non-null  datetime64[ns, UTC]
 17  payment_method     137 non-null    object
 18  agent_id           19910 non-null  object
 19  broker_id          19910 non-null  object
dtypes: bool(2), datetime64[ns, UTC](1), float64(6), object(11)
memory usage: 2.9+ MB

In [ ]:

for dataframe in [df_rent, df_buy]:
  dataframe['furnished'] = dataframe['furnished'].fillna('Unknown')
  dataframe['district'] = dataframe['district'].fillna('Unknown')
 

df_buy['completion_status'] = df_buy['completion_status'].fillna('Unknown')
df_rent['payment_method'] = df_rent['payment_method'].fillna('Unspecified')

In [24]:
print(f'Duplicates in Rent dataset: {df_rent.duplicated().sum()}')
print(f'Duplicates in Buy dataset: {df_buy.duplicated().sum()}')

Duplicates in Rent dataset: 8
Duplicates in Buy dataset: 28

In [25]:
df_rent.drop_duplicates(inplace=True)
df_buy.drop_duplicates(inplace=True)

C:\Users\dell\AppData\Local\Temp\ipykernel_15236\3767002022.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rent.drop_duplicates(inplace=True)
C:\Users\dell\AppData\Local\Temp\ipykernel_15236\3767002022.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_buy.drop_duplicates(inplace=True)

In [35]:
df_buy['offering_type'].nunique()

1

In [27]:

df_buy[df['bedrooms'].isna()]
pd.set_option('display.max_rows',20)
pd.set_option('display.min_rows',20)

C:\Users\dell\AppData\Local\Temp\ipykernel_15236\871190154.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_buy[df['bedrooms'].isna()]

In [28]:
df_buy[df_buy['property_type']=='Land']

,category,property_type,offering_type,completion_status,price_egp,city,town,district,lat,lon,bedrooms,bathrooms,area_value,furnished,listing_level,is_premium,is_featured,listed_date,payment_method,agent_id,broker_id
3219,buy,Land,Residential for Sale,Unknown,11300000.0,Cairo,New Cairo City,The 5th Settlement,30.060677,31.551458,NaN,NaN,450.0,Unknown,premium,True,False,2026-02-15 12:12:56+00:00,cash,47176,5253
3259,buy,Land,Residential for Sale,Unknown,67500000.0,Giza,6 October City,1st District,29.961863,30.955711,NaN,NaN,1500.0,Unknown,premium,True,False,2026-01-22 17:24:53+00:00,cash,36502,4226
4064,buy,Land,Residential for Sale,Unknown,10500000.0,Giza,6 October City,Hadayek October,29.914593,31.071655,NaN,NaN,426.0,Unknown,featured,False,True,2026-02-26 10:21:56+00:00,cash,72021,6399
5609,buy,Land,Residential for Sale,Unknown,265000000.0,North Coast,Al Alamein,Unknown,30.822470,28.954309,NaN,NaN,10600.0,Unknown,featured,False,True,2026-02-11 23:07:37+00:00,cash,68246,6316
5722,buy,Land,Residential for Sale,Unknown,2400000.0,Giza,6 October City,New October City,29.900145,30.795343,NaN,NaN,311.0,Unknown,featured,False,True,2026-01-20 11:34:18+00:00,cash | installments,71946,6031
5730,buy,Land,Residential for Sale,Unknown,14600000.0,Cairo,New Cairo City,The 5th Settlement,30.060677,31.551458,NaN,NaN,935.0,Unknown,featured,False,True,2026-03-01 10:04:26+00:00,cash,58306,2832
5742,buy,Land,Residential for Sale,Unknown,15000000.0,Cairo,New Cairo City,The 5th Settlement,30.060677,31.551458,NaN,NaN,495.0,Unknown,featured,False,True,2026-03-03 12:59:22+00:00,cash,43540,1393
5820,buy,Land,Residential for Sale,Unknown,2250000.0,Giza,6 October City,New October City,29.900145,30.795343,NaN,NaN,100.0,Unknown,featured,False,True,2026-02-25 22:39:53+00:00,installments,49913,5527
5894,buy,Land,Residential for Sale,Unknown,3100000.0,Giza,6 October City,New October City,29.900145,30.795343,NaN,NaN,311.0,Unknown,featured,False,True,2026-02-24 22:51:16+00:00,cash,31467,3014
5895,buy,Land,Residential for Sale,Unknown,3000000.0,Giza,6 October City,Green Belt,29.890285,30.836920,NaN,NaN,311.0,Unknown,featured,False,True,2026-02-24 22:41:57+00:00,cash,31467,3014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10358,buy,Land,Residential for Sale,Unknown,940000000.0,Giza,6 October City,Al Wahat Road,29.957909,30.915758,NaN,NaN,96600.0,Unknown,standard,False,False,2026-03-03 13:32:48+00:00,cash,53051,5778
10419,buy,Land,Residential for Sale,Unknown,140000000.0,Giza,6 October City,Green Belt,30.029922,30.935926,NaN,NaN,21000.0,Unknown,standard,False,False,2026-03-03 13:21:08+00:00,cash,53051,5778
10482,buy,Land,Residential for Sale,Unknown,140000000.0,Giza,6 October City,Green Belt,30.029922,30.935926,NaN,NaN,21000.0,Unknown,standard,False,False,2026-03-03 13:11:44+00:00,cash,53051,5778
10500,buy,Land,Residential for Sale,Unknown,400000000.0,Giza,6 October City,Green Belt,30.059566,30.927748,NaN,NaN,42000.0,Unknown,standard,False,False,2026-03-03 13:07:19+00:00,cash,53051,5778
11206,buy,Land,Residential for Sale,Unknown,770400000.0,Giza,Sheikh Zayed City,Riviera City,30.049547,31.045544,NaN,NaN,38520.0,Unknown,standard,False,False,2026-03-03 11:37:07+00:00,cash,53051,5778
11568,buy,Land,Residential for Sale,Unknown,75000000.0,Giza,6 October City,Cairo Alexandria Desert Road,30.006905,31.059334,NaN,NaN,1360.0,Unknown,standard,False,False,2026-03-03 10:40:52+00:00,cash,26955,2671
15908,buy,Land,Residential for Sale,Unknown,18000000.0,Cairo,New Cairo City,The 5th Settlement,30.060677,31.551458,NaN,NaN,759.0,Unknown,standard,False,False,2026-03-01 14:15:41+00:00,cash,44226,4963
17634,buy,Land,Residential for Sale,Unknown,120000000.0,Giza,6 October City,Green Belt,30.027306,30.929413,NaN,NaN,14000.0,Unknown,standard,False,False,2026-03-01 01:40:51+00:00,cash,58527,5778
18151,buy,Land,Residential for Sale,Unknown,23000000.0,Cairo,New Cairo City,The 5th Settlement,30.060677,31.551458,NaN,NaN,765.0,Unknown,standard,False,False,2026-02-28 14:54:14+00:00,cash,44226,4963
18838,buy,Land,Residential for Sale,Unknown,85000000.0,Cairo,El Nozha,Sheraton Al Matar,30.101929,31.366772,NaN,NaN,1378.0,Unknown,standard,False,False,2026-02-28 10:43:09+00:00,cash,47149,1321

In [50]:
df_rent['completion_status'] = df_rent['completion_status'].fillna('completed')

C:\Users\dell\AppData\Local\Temp\ipykernel_15236\4265455706.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rent['completion_status'] = df_rent['completion_status'].fillna('completed')

In [51]:
df_rent.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19902 entries, 19803 to 39712
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   category           19902 non-null  object
 1   property_type      19902 non-null  object
 2   completion_status  19902 non-null  object
 3   price_egp          19902 non-null  float64
 4   city               19902 non-null  object
 5   town               19902 non-null  object
 6   district           19902 non-null  object
 7   lat                19902 non-null  float64
 8   lon                19902 non-null  float64
 9   bedrooms           19167 non-null  float64
 10  bathrooms          19817 non-null  float64
 11  area_value         19902 non-null  float64
 12  furnished          19902 non-null  object
 13  listing_level      19902 non-null  object
 14  is_premium         19902 non-null  bool
 15  is_featured        19902 non-null  bool
 16  listed_date        19902 non-null  datetime64[ns, UTC]
 17  payment_method     19902 non-null  object
 18  agent_id           19902 non-null  object
 19  broker_id          19902 non-null  object
dtypes: bool(2), datetime64[ns, UTC](1), float64(6), object(11)
memory usage: 2.9+ MB

In [57]:
df_buy['offering_type'].nunique()

1

In [59]:
df_buy.drop(columns=['offering_type'],inplace=True)

C:\Users\dell\AppData\Local\Temp\ipykernel_15236\3263461086.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_buy.drop(columns=['offering_type'],inplace=True)

In [61]:
from pandas import isna
df_rent[df_rent['bedrooms'].isna()]

,category,property_type,completion_status,price_egp,city,town,district,lat,lon,bedrooms,bathrooms,area_value,furnished,listing_level,is_premium,is_featured,listed_date,payment_method,agent_id,broker_id
19813,rent,Apartment,completed,22000.0,Cairo,New Cairo City,Abou El Houl,29.982248,31.468801,NaN,1.0,80.0,YES,premium,True,False,2026-03-04 19:14:44+00:00,Unspecified,68620,6317
19820,rent,Apartment,completed,40000.0,Cairo,New Cairo City,The 5th Settlement,30.022596,31.545815,NaN,1.0,70.0,YES,premium,True,False,2026-03-04 15:43:15+00:00,Unspecified,49922,5528
19825,rent,Apartment,completed,25000.0,Cairo,New Cairo City,The 5th Settlement,30.051462,31.538992,NaN,1.0,78.0,NO,premium,True,False,2026-03-02 12:40:26+00:00,Unspecified,34457,3767
19871,rent,Apartment,completed,20000.0,Cairo,New Cairo City,The 5th Settlement,30.008648,31.428759,NaN,1.0,100.0,YES,premium,True,False,2026-03-03 09:55:46+00:00,Unspecified,44158,2520
19886,rent,Apartment,completed,25000.0,Cairo,New Cairo City,The 5th Settlement,30.008329,31.410305,NaN,1.0,90.0,YES,premium,True,False,2026-03-02 20:39:08+00:00,Unspecified,30864,2133
19936,rent,Apartment,completed,27000.0,Cairo,New Cairo City,Al Narges,30.001871,31.454647,NaN,1.0,60.0,YES,premium,True,False,2026-03-01 12:20:40+00:00,Unspecified,66449,2520
19969,rent,Apartment,completed,27000.0,Cairo,New Cairo City,Al Narges,30.001871,31.454647,NaN,1.0,60.0,YES,premium,True,False,2026-03-01 12:14:14+00:00,Unspecified,50635,2520
19987,rent,Apartment,completed,18000.0,Cairo,New Cairo City,The 5th Settlement,30.006369,31.500866,NaN,1.0,60.0,YES,premium,True,False,2026-02-28 14:38:47+00:00,Unspecified,30864,2133
20006,rent,Apartment,completed,38000.0,Cairo,New Cairo City,The 5th Settlement,30.022596,31.545815,NaN,1.0,80.0,YES,premium,True,False,2026-02-27 21:51:44+00:00,Unspecified,33270,3882
20023,rent,Apartment,completed,16000.0,Cairo,New Cairo City,Abou El Houl,29.982248,31.468801,NaN,1.0,50.0,YES,premium,True,False,2026-02-26 08:59:37+00:00,Unspecified,55358,177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39615,rent,Apartment,completed,50000.0,Cairo,New Cairo City,The 5th Settlement,30.022596,31.545815,NaN,1.0,55.0,YES,standard,False,False,2026-02-07 19:14:58+00:00,Unspecified,8055,566
39626,rent,Penthouse,completed,47000.0,Cairo,New Cairo City,The 5th Settlement,30.022596,31.545815,NaN,1.0,55.0,YES,standard,False,False,2026-02-07 19:00:20+00:00,Unspecified,8052,566
39627,rent,Apartment,completed,47000.0,Cairo,New Cairo City,The 5th Settlement,30.022596,31.545815,NaN,1.0,57.0,YES,standard,False,False,2026-02-07 18:57:13+00:00,Unspecified,8055,566
39629,rent,Apartment,completed,45000.0,Cairo,New Cairo City,The 5th Settlement,30.025890,31.497156,NaN,1.0,80.0,YES,standard,False,False,2026-02-07 18:54:14+00:00,Unspecified,48954,4950
39644,rent,Apartment,completed,45000.0,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,30.046803,31.002106,NaN,1.0,60.0,YES,standard,False,False,2026-02-07 18:30:23+00:00,Unspecified,67250,430
39646,rent,Apartment,completed,45000.0,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,30.046803,31.002106,NaN,1.0,60.0,YES,standard,False,False,2026-02-07 18:27:30+00:00,Unspecified,67250,430
39675,rent,Apartment,completed,16500.0,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,30.040565,30.990543,NaN,1.0,35.0,PARTLY,standard,False,False,2026-02-07 17:38:24+00:00,Unspecified,67250,430
39680,rent,Apartment,completed,22000.0,Giza,6 October City,Al Wahat Road,29.972370,31.026577,NaN,1.0,88.0,YES,standard,False,False,2026-02-07 17:28:43+00:00,Unspecified,38445,4388
39692,rent,Apartment,completed,40000.0,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,30.046803,31.002106,NaN,1.0,58.0,YES,standard,False,False,2026-02-07 17:09:51+00:00,Unspecified,67250,430
39698,rent,Apartment,completed,29000.0,Cairo,Madinaty,Privado,30.091936,31.665174,NaN,1.0,69.0,YES,standard,False,False,2026-02-07 17:01:46+00:00,Unspecified,57257,4760